// Code generated by ogen, DO NOT EDIT.
package fcpm

type GetFcpmV2OrgComputePoolConfigRes interface {
	getFcpmV2OrgComputePoolConfigRes()
}

type UpdateFcpmV2OrgComputePoolConfigRes interface {
	updateFcpmV2OrgComputePoolConfigRes()
}
