// Code generated by ogen, DO NOT EDIT.

package cdx

import (
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for CdxV1ProviderShareStatus using FNV-1a.
// Equal objects must produce equal hashes.
func (a CdxV1ProviderShareStatus) Hash() uint64 {
	h := fnv.New64a()

	// Hash primitive field: Phase
	h.Write([]byte(fmt.Sprintf("%v", a.Phase)))
	return h.Sum64()
}
