// Code generated by ogen, DO NOT EDIT.

package rtce

import (
	"net/url"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// BadRequestErrorHeaders wraps Failure with response headers.
type BadRequestErrorHeaders struct {
	XRequestID OptString
	Response   Failure
}

// GetXRequestID returns the value of XRequestID.
func (s *BadRequestErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *BadRequestErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *BadRequestErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *BadRequestErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*BadRequestErrorHeaders) createRtceV1RtceTopicRes() {}
func (*BadRequestErrorHeaders) deleteRtceV1RtceTopicRes() {}
func (*BadRequestErrorHeaders) getRtceV1RtceTopicRes()    {}
func (*BadRequestErrorHeaders) listRtceV1RtceTopicsRes()  {}
func (*BadRequestErrorHeaders) updateRtceV1RtceTopicRes() {}

// ConflictErrorHeaders wraps Failure with response headers.
type ConflictErrorHeaders struct {
	Location   OptURI
	XRequestID OptString
	Response   Failure
}

// GetLocation returns the value of Location.
func (s *ConflictErrorHeaders) GetLocation() OptURI {
	return s.Location
}

// GetXRequestID returns the value of XRequestID.
func (s *ConflictErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *ConflictErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetLocation sets the value of Location.
func (s *ConflictErrorHeaders) SetLocation(val OptURI) {
	s.Location = val
}

// SetXRequestID sets the value of XRequestID.
func (s *ConflictErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *ConflictErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*ConflictErrorHeaders) createRtceV1RtceTopicRes() {}
func (*ConflictErrorHeaders) updateRtceV1RtceTopicRes() {}

// Merged schema.
type CreateRtceV1RtceTopicAccepted struct {
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion OptCreateRtceV1RtceTopicAcceptedAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind     OptCreateRtceV1RtceTopicAcceptedKind `json:"kind"`
	Metadata jx.Raw                               `json:"metadata"`
	// Merged property.
	Spec   CreateRtceV1RtceTopicAcceptedSpec `json:"spec"`
	Status RtceV1RtceTopicStatus             `json:"status"`
}

// GetAPIVersion returns the value of APIVersion.
func (s *CreateRtceV1RtceTopicAccepted) GetAPIVersion() OptCreateRtceV1RtceTopicAcceptedAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *CreateRtceV1RtceTopicAccepted) GetKind() OptCreateRtceV1RtceTopicAcceptedKind {
	return s.Kind
}

// GetMetadata returns the value of Metadata.
func (s *CreateRtceV1RtceTopicAccepted) GetMetadata() jx.Raw {
	return s.Metadata
}

// GetSpec returns the value of Spec.
func (s *CreateRtceV1RtceTopicAccepted) GetSpec() CreateRtceV1RtceTopicAcceptedSpec {
	return s.Spec
}

// GetStatus returns the value of Status.
func (s *CreateRtceV1RtceTopicAccepted) GetStatus() RtceV1RtceTopicStatus {
	return s.Status
}

// SetAPIVersion sets the value of APIVersion.
func (s *CreateRtceV1RtceTopicAccepted) SetAPIVersion(val OptCreateRtceV1RtceTopicAcceptedAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *CreateRtceV1RtceTopicAccepted) SetKind(val OptCreateRtceV1RtceTopicAcceptedKind) {
	s.Kind = val
}

// SetMetadata sets the value of Metadata.
func (s *CreateRtceV1RtceTopicAccepted) SetMetadata(val jx.Raw) {
	s.Metadata = val
}

// SetSpec sets the value of Spec.
func (s *CreateRtceV1RtceTopicAccepted) SetSpec(val CreateRtceV1RtceTopicAcceptedSpec) {
	s.Spec = val
}

// SetStatus sets the value of Status.
func (s *CreateRtceV1RtceTopicAccepted) SetStatus(val RtceV1RtceTopicStatus) {
	s.Status = val
}

// APIVersion defines the schema version of this representation of a resource.
type CreateRtceV1RtceTopicAcceptedAPIVersion string

const (
	CreateRtceV1RtceTopicAcceptedAPIVersionRtceV1 CreateRtceV1RtceTopicAcceptedAPIVersion = "rtce/v1"
)

// AllValues returns all CreateRtceV1RtceTopicAcceptedAPIVersion values.
func (CreateRtceV1RtceTopicAcceptedAPIVersion) AllValues() []CreateRtceV1RtceTopicAcceptedAPIVersion {
	return []CreateRtceV1RtceTopicAcceptedAPIVersion{
		CreateRtceV1RtceTopicAcceptedAPIVersionRtceV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateRtceV1RtceTopicAcceptedAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case CreateRtceV1RtceTopicAcceptedAPIVersionRtceV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateRtceV1RtceTopicAcceptedAPIVersion) UnmarshalText(data []byte) error {
	switch CreateRtceV1RtceTopicAcceptedAPIVersion(data) {
	case CreateRtceV1RtceTopicAcceptedAPIVersionRtceV1:
		*s = CreateRtceV1RtceTopicAcceptedAPIVersionRtceV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// CreateRtceV1RtceTopicAcceptedHeaders wraps CreateRtceV1RtceTopicAccepted with response headers.
type CreateRtceV1RtceTopicAcceptedHeaders struct {
	Location            OptURI
	XRateLimitLimit     OptInt
	XRateLimitRemaining OptInt
	XRateLimitReset     OptInt
	XRequestID          OptString
	Response            CreateRtceV1RtceTopicAccepted
}

// GetLocation returns the value of Location.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) GetLocation() OptURI {
	return s.Location
}

// GetXRateLimitLimit returns the value of XRateLimitLimit.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) GetXRateLimitLimit() OptInt {
	return s.XRateLimitLimit
}

// GetXRateLimitRemaining returns the value of XRateLimitRemaining.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) GetXRateLimitRemaining() OptInt {
	return s.XRateLimitRemaining
}

// GetXRateLimitReset returns the value of XRateLimitReset.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) GetXRateLimitReset() OptInt {
	return s.XRateLimitReset
}

// GetXRequestID returns the value of XRequestID.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) GetResponse() CreateRtceV1RtceTopicAccepted {
	return s.Response
}

// SetLocation sets the value of Location.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) SetLocation(val OptURI) {
	s.Location = val
}

// SetXRateLimitLimit sets the value of XRateLimitLimit.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) SetXRateLimitLimit(val OptInt) {
	s.XRateLimitLimit = val
}

// SetXRateLimitRemaining sets the value of XRateLimitRemaining.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) SetXRateLimitRemaining(val OptInt) {
	s.XRateLimitRemaining = val
}

// SetXRateLimitReset sets the value of XRateLimitReset.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) SetXRateLimitReset(val OptInt) {
	s.XRateLimitReset = val
}

// SetXRequestID sets the value of XRequestID.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *CreateRtceV1RtceTopicAcceptedHeaders) SetResponse(val CreateRtceV1RtceTopicAccepted) {
	s.Response = val
}

func (*CreateRtceV1RtceTopicAcceptedHeaders) createRtceV1RtceTopicRes() {}

// Kind defines the object this REST resource represents.
type CreateRtceV1RtceTopicAcceptedKind string

const (
	CreateRtceV1RtceTopicAcceptedKindRtceTopic CreateRtceV1RtceTopicAcceptedKind = "RtceTopic"
)

// AllValues returns all CreateRtceV1RtceTopicAcceptedKind values.
func (CreateRtceV1RtceTopicAcceptedKind) AllValues() []CreateRtceV1RtceTopicAcceptedKind {
	return []CreateRtceV1RtceTopicAcceptedKind{
		CreateRtceV1RtceTopicAcceptedKindRtceTopic,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateRtceV1RtceTopicAcceptedKind) MarshalText() ([]byte, error) {
	switch s {
	case CreateRtceV1RtceTopicAcceptedKindRtceTopic:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateRtceV1RtceTopicAcceptedKind) UnmarshalText(data []byte) error {
	switch CreateRtceV1RtceTopicAcceptedKind(data) {
	case CreateRtceV1RtceTopicAcceptedKindRtceTopic:
		*s = CreateRtceV1RtceTopicAcceptedKindRtceTopic
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type CreateRtceV1RtceTopicAcceptedSpec struct {
	// Merged property.
	Environment EnvScopedObjectReference `json:"environment"`
	// Merged property.
	KafkaCluster EnvScopedObjectReference `json:"kafka_cluster"`
	// The cloud provider where the RTCE topic is deployed.
	Cloud string `json:"cloud"`
	// The cloud region where the RTCE topic is deployed.
	Region string `json:"region"`
	// The Kafka topic name containing the data for the RTCE topic.
	TopicName string `json:"topic_name"`
	// A model-readable description of the RTCE topic.
	Description string `json:"description"`
}

// GetEnvironment returns the value of Environment.
func (s *CreateRtceV1RtceTopicAcceptedSpec) GetEnvironment() EnvScopedObjectReference {
	return s.Environment
}

// GetKafkaCluster returns the value of KafkaCluster.
func (s *CreateRtceV1RtceTopicAcceptedSpec) GetKafkaCluster() EnvScopedObjectReference {
	return s.KafkaCluster
}

// GetCloud returns the value of Cloud.
func (s *CreateRtceV1RtceTopicAcceptedSpec) GetCloud() string {
	return s.Cloud
}

// GetRegion returns the value of Region.
func (s *CreateRtceV1RtceTopicAcceptedSpec) GetRegion() string {
	return s.Region
}

// GetTopicName returns the value of TopicName.
func (s *CreateRtceV1RtceTopicAcceptedSpec) GetTopicName() string {
	return s.TopicName
}

// GetDescription returns the value of Description.
func (s *CreateRtceV1RtceTopicAcceptedSpec) GetDescription() string {
	return s.Description
}

// SetEnvironment sets the value of Environment.
func (s *CreateRtceV1RtceTopicAcceptedSpec) SetEnvironment(val EnvScopedObjectReference) {
	s.Environment = val
}

// SetKafkaCluster sets the value of KafkaCluster.
func (s *CreateRtceV1RtceTopicAcceptedSpec) SetKafkaCluster(val EnvScopedObjectReference) {
	s.KafkaCluster = val
}

// SetCloud sets the value of Cloud.
func (s *CreateRtceV1RtceTopicAcceptedSpec) SetCloud(val string) {
	s.Cloud = val
}

// SetRegion sets the value of Region.
func (s *CreateRtceV1RtceTopicAcceptedSpec) SetRegion(val string) {
	s.Region = val
}

// SetTopicName sets the value of TopicName.
func (s *CreateRtceV1RtceTopicAcceptedSpec) SetTopicName(val string) {
	s.TopicName = val
}

// SetDescription sets the value of Description.
func (s *CreateRtceV1RtceTopicAcceptedSpec) SetDescription(val string) {
	s.Description = val
}

// Merged schema.
type CreateRtceV1RtceTopicReq struct {
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion OptCreateRtceV1RtceTopicReqAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind     OptCreateRtceV1RtceTopicReqKind `json:"kind"`
	Metadata jx.Raw                          `json:"metadata"`
	// Merged property.
	Spec   CreateRtceV1RtceTopicReqSpec `json:"spec"`
	Status OptRtceV1RtceTopicStatus     `json:"status"`
}

// GetAPIVersion returns the value of APIVersion.
func (s *CreateRtceV1RtceTopicReq) GetAPIVersion() OptCreateRtceV1RtceTopicReqAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *CreateRtceV1RtceTopicReq) GetKind() OptCreateRtceV1RtceTopicReqKind {
	return s.Kind
}

// GetMetadata returns the value of Metadata.
func (s *CreateRtceV1RtceTopicReq) GetMetadata() jx.Raw {
	return s.Metadata
}

// GetSpec returns the value of Spec.
func (s *CreateRtceV1RtceTopicReq) GetSpec() CreateRtceV1RtceTopicReqSpec {
	return s.Spec
}

// GetStatus returns the value of Status.
func (s *CreateRtceV1RtceTopicReq) GetStatus() OptRtceV1RtceTopicStatus {
	return s.Status
}

// SetAPIVersion sets the value of APIVersion.
func (s *CreateRtceV1RtceTopicReq) SetAPIVersion(val OptCreateRtceV1RtceTopicReqAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *CreateRtceV1RtceTopicReq) SetKind(val OptCreateRtceV1RtceTopicReqKind) {
	s.Kind = val
}

// SetMetadata sets the value of Metadata.
func (s *CreateRtceV1RtceTopicReq) SetMetadata(val jx.Raw) {
	s.Metadata = val
}

// SetSpec sets the value of Spec.
func (s *CreateRtceV1RtceTopicReq) SetSpec(val CreateRtceV1RtceTopicReqSpec) {
	s.Spec = val
}

// SetStatus sets the value of Status.
func (s *CreateRtceV1RtceTopicReq) SetStatus(val OptRtceV1RtceTopicStatus) {
	s.Status = val
}

// APIVersion defines the schema version of this representation of a resource.
type CreateRtceV1RtceTopicReqAPIVersion string

const (
	CreateRtceV1RtceTopicReqAPIVersionRtceV1 CreateRtceV1RtceTopicReqAPIVersion = "rtce/v1"
)

// AllValues returns all CreateRtceV1RtceTopicReqAPIVersion values.
func (CreateRtceV1RtceTopicReqAPIVersion) AllValues() []CreateRtceV1RtceTopicReqAPIVersion {
	return []CreateRtceV1RtceTopicReqAPIVersion{
		CreateRtceV1RtceTopicReqAPIVersionRtceV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateRtceV1RtceTopicReqAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case CreateRtceV1RtceTopicReqAPIVersionRtceV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateRtceV1RtceTopicReqAPIVersion) UnmarshalText(data []byte) error {
	switch CreateRtceV1RtceTopicReqAPIVersion(data) {
	case CreateRtceV1RtceTopicReqAPIVersionRtceV1:
		*s = CreateRtceV1RtceTopicReqAPIVersionRtceV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Kind defines the object this REST resource represents.
type CreateRtceV1RtceTopicReqKind string

const (
	CreateRtceV1RtceTopicReqKindRtceTopic CreateRtceV1RtceTopicReqKind = "RtceTopic"
)

// AllValues returns all CreateRtceV1RtceTopicReqKind values.
func (CreateRtceV1RtceTopicReqKind) AllValues() []CreateRtceV1RtceTopicReqKind {
	return []CreateRtceV1RtceTopicReqKind{
		CreateRtceV1RtceTopicReqKindRtceTopic,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateRtceV1RtceTopicReqKind) MarshalText() ([]byte, error) {
	switch s {
	case CreateRtceV1RtceTopicReqKindRtceTopic:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateRtceV1RtceTopicReqKind) UnmarshalText(data []byte) error {
	switch CreateRtceV1RtceTopicReqKind(data) {
	case CreateRtceV1RtceTopicReqKindRtceTopic:
		*s = CreateRtceV1RtceTopicReqKindRtceTopic
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type CreateRtceV1RtceTopicReqSpec struct {
	// Merged property.
	Environment EnvScopedObjectReference `json:"environment"`
	// Merged property.
	KafkaCluster EnvScopedObjectReference `json:"kafka_cluster"`
	// The cloud provider where the RTCE topic is deployed.
	Cloud string `json:"cloud"`
	// The cloud region where the RTCE topic is deployed.
	Region string `json:"region"`
	// The Kafka topic name containing the data for the RTCE topic.
	TopicName string `json:"topic_name"`
	// A model-readable description of the RTCE topic.
	Description string `json:"description"`
}

// GetEnvironment returns the value of Environment.
func (s *CreateRtceV1RtceTopicReqSpec) GetEnvironment() EnvScopedObjectReference {
	return s.Environment
}

// GetKafkaCluster returns the value of KafkaCluster.
func (s *CreateRtceV1RtceTopicReqSpec) GetKafkaCluster() EnvScopedObjectReference {
	return s.KafkaCluster
}

// GetCloud returns the value of Cloud.
func (s *CreateRtceV1RtceTopicReqSpec) GetCloud() string {
	return s.Cloud
}

// GetRegion returns the value of Region.
func (s *CreateRtceV1RtceTopicReqSpec) GetRegion() string {
	return s.Region
}

// GetTopicName returns the value of TopicName.
func (s *CreateRtceV1RtceTopicReqSpec) GetTopicName() string {
	return s.TopicName
}

// GetDescription returns the value of Description.
func (s *CreateRtceV1RtceTopicReqSpec) GetDescription() string {
	return s.Description
}

// SetEnvironment sets the value of Environment.
func (s *CreateRtceV1RtceTopicReqSpec) SetEnvironment(val EnvScopedObjectReference) {
	s.Environment = val
}

// SetKafkaCluster sets the value of KafkaCluster.
func (s *CreateRtceV1RtceTopicReqSpec) SetKafkaCluster(val EnvScopedObjectReference) {
	s.KafkaCluster = val
}

// SetCloud sets the value of Cloud.
func (s *CreateRtceV1RtceTopicReqSpec) SetCloud(val string) {
	s.Cloud = val
}

// SetRegion sets the value of Region.
func (s *CreateRtceV1RtceTopicReqSpec) SetRegion(val string) {
	s.Region = val
}

// SetTopicName sets the value of TopicName.
func (s *CreateRtceV1RtceTopicReqSpec) SetTopicName(val string) {
	s.TopicName = val
}

// SetDescription sets the value of Description.
func (s *CreateRtceV1RtceTopicReqSpec) SetDescription(val string) {
	s.Description = val
}

// DefaultSystemErrorHeaders wraps Failure with response headers.
type DefaultSystemErrorHeaders struct {
	XRequestID OptString
	Response   Failure
}

// GetXRequestID returns the value of XRequestID.
func (s *DefaultSystemErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *DefaultSystemErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *DefaultSystemErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *DefaultSystemErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*DefaultSystemErrorHeaders) createRtceV1RtceTopicRes() {}
func (*DefaultSystemErrorHeaders) deleteRtceV1RtceTopicRes() {}
func (*DefaultSystemErrorHeaders) getRtceV1RtceTopicRes()    {}
func (*DefaultSystemErrorHeaders) listRtceV1RtceTopicsRes()  {}
func (*DefaultSystemErrorHeaders) updateRtceV1RtceTopicRes() {}

// DeleteRtceV1RtceTopicNoContent is response for DeleteRtceV1RtceTopic operation.
type DeleteRtceV1RtceTopicNoContent struct {
	XRateLimitLimit     OptInt
	XRateLimitRemaining OptInt
	XRateLimitReset     OptInt
	XRequestID          OptString
}

// GetXRateLimitLimit returns the value of XRateLimitLimit.
func (s *DeleteRtceV1RtceTopicNoContent) GetXRateLimitLimit() OptInt {
	return s.XRateLimitLimit
}

// GetXRateLimitRemaining returns the value of XRateLimitRemaining.
func (s *DeleteRtceV1RtceTopicNoContent) GetXRateLimitRemaining() OptInt {
	return s.XRateLimitRemaining
}

// GetXRateLimitReset returns the value of XRateLimitReset.
func (s *DeleteRtceV1RtceTopicNoContent) GetXRateLimitReset() OptInt {
	return s.XRateLimitReset
}

// GetXRequestID returns the value of XRequestID.
func (s *DeleteRtceV1RtceTopicNoContent) GetXRequestID() OptString {
	return s.XRequestID
}

// SetXRateLimitLimit sets the value of XRateLimitLimit.
func (s *DeleteRtceV1RtceTopicNoContent) SetXRateLimitLimit(val OptInt) {
	s.XRateLimitLimit = val
}

// SetXRateLimitRemaining sets the value of XRateLimitRemaining.
func (s *DeleteRtceV1RtceTopicNoContent) SetXRateLimitRemaining(val OptInt) {
	s.XRateLimitRemaining = val
}

// SetXRateLimitReset sets the value of XRateLimitReset.
func (s *DeleteRtceV1RtceTopicNoContent) SetXRateLimitReset(val OptInt) {
	s.XRateLimitReset = val
}

// SetXRequestID sets the value of XRequestID.
func (s *DeleteRtceV1RtceTopicNoContent) SetXRequestID(val OptString) {
	s.XRequestID = val
}

func (*DeleteRtceV1RtceTopicNoContent) deleteRtceV1RtceTopicRes() {}

// ObjectReference provides information for you to locate the referred object.
// Ref: #/components/schemas/EnvScopedObjectReference
type EnvScopedObjectReference struct {
	// ID of the referred resource.
	ID string `json:"id"`
	// Environment of the referred resource, if env-scoped.
	Environment OptString `json:"environment"`
	// API URL for accessing or modifying the referred object.
	Related url.URL `json:"related"`
	// CRN reference to the referred resource.
	ResourceName url.URL `json:"resource_name"`
}

// GetID returns the value of ID.
func (s *EnvScopedObjectReference) GetID() string {
	return s.ID
}

// GetEnvironment returns the value of Environment.
func (s *EnvScopedObjectReference) GetEnvironment() OptString {
	return s.Environment
}

// GetRelated returns the value of Related.
func (s *EnvScopedObjectReference) GetRelated() url.URL {
	return s.Related
}

// GetResourceName returns the value of ResourceName.
func (s *EnvScopedObjectReference) GetResourceName() url.URL {
	return s.ResourceName
}

// SetID sets the value of ID.
func (s *EnvScopedObjectReference) SetID(val string) {
	s.ID = val
}

// SetEnvironment sets the value of Environment.
func (s *EnvScopedObjectReference) SetEnvironment(val OptString) {
	s.Environment = val
}

// SetRelated sets the value of Related.
func (s *EnvScopedObjectReference) SetRelated(val url.URL) {
	s.Related = val
}

// SetResourceName sets the value of ResourceName.
func (s *EnvScopedObjectReference) SetResourceName(val url.URL) {
	s.ResourceName = val
}

// Describes a particular error encountered while performing an operation.
// Ref: #/components/schemas/Error
type Error struct {
	// A unique identifier for this particular occurrence of the problem.
	ID OptString `json:"id"`
	// The HTTP status code applicable to this problem, expressed as a string value.
	Status OptString `json:"status"`
	// An application-specific error code, expressed as a string value.
	Code OptString `json:"code"`
	// A short, human-readable summary of the problem. It SHOULD NOT change from occurrence to occurrence
	// of the problem, except for purposes of localization.
	Title OptString `json:"title"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail OptString `json:"detail"`
	// If this error was caused by a particular part of the API request, the source will point to the query
	// string parameter or request body property that caused it.
	Source    OptErrorSource `json:"source"`
	ErrorCode OptInt32       `json:"error_code"`
	Message   OptNilString   `json:"message"`
}

// GetID returns the value of ID.
func (s *Error) GetID() OptString {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *Error) GetStatus() OptString {
	return s.Status
}

// GetCode returns the value of Code.
func (s *Error) GetCode() OptString {
	return s.Code
}

// GetTitle returns the value of Title.
func (s *Error) GetTitle() OptString {
	return s.Title
}

// GetDetail returns the value of Detail.
func (s *Error) GetDetail() OptString {
	return s.Detail
}

// GetSource returns the value of Source.
func (s *Error) GetSource() OptErrorSource {
	return s.Source
}

// GetErrorCode returns the value of ErrorCode.
func (s *Error) GetErrorCode() OptInt32 {
	return s.ErrorCode
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() OptNilString {
	return s.Message
}

// SetID sets the value of ID.
func (s *Error) SetID(val OptString) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *Error) SetStatus(val OptString) {
	s.Status = val
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val OptString) {
	s.Code = val
}

// SetTitle sets the value of Title.
func (s *Error) SetTitle(val OptString) {
	s.Title = val
}

// SetDetail sets the value of Detail.
func (s *Error) SetDetail(val OptString) {
	s.Detail = val
}

// SetSource sets the value of Source.
func (s *Error) SetSource(val OptErrorSource) {
	s.Source = val
}

// SetErrorCode sets the value of ErrorCode.
func (s *Error) SetErrorCode(val OptInt32) {
	s.ErrorCode = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val OptNilString) {
	s.Message = val
}

// If this error was caused by a particular part of the API request, the source will point to the query
// string parameter or request body property that caused it.
type ErrorSource struct {
	// A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/spec" for a spec
	// object, or "/spec/title" for a specific field].
	Pointer OptString `json:"pointer"`
	// A string indicating which query parameter caused the error.
	Parameter OptString `json:"parameter"`
}

// GetPointer returns the value of Pointer.
func (s *ErrorSource) GetPointer() OptString {
	return s.Pointer
}

// GetParameter returns the value of Parameter.
func (s *ErrorSource) GetParameter() OptString {
	return s.Parameter
}

// SetPointer sets the value of Pointer.
func (s *ErrorSource) SetPointer(val OptString) {
	s.Pointer = val
}

// SetParameter sets the value of Parameter.
func (s *ErrorSource) SetParameter(val OptString) {
	s.Parameter = val
}

// Provides information about problems encountered while performing an operation.
// Ref: #/components/schemas/Failure
type Failure struct {
	// List of errors which caused this operation to fail.
	Errors []Error `json:"errors"`
}

// GetErrors returns the value of Errors.
func (s *Failure) GetErrors() []Error {
	return s.Errors
}

// SetErrors sets the value of Errors.
func (s *Failure) SetErrors(val []Error) {
	s.Errors = val
}

// Merged schema.
type GetRtceV1RtceTopicOK struct {
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion GetRtceV1RtceTopicOKAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind     GetRtceV1RtceTopicOKKind `json:"kind"`
	Metadata jx.Raw                   `json:"metadata"`
	// Merged property.
	Spec   GetRtceV1RtceTopicOKSpec `json:"spec"`
	Status RtceV1RtceTopicStatus    `json:"status"`
}

// GetAPIVersion returns the value of APIVersion.
func (s *GetRtceV1RtceTopicOK) GetAPIVersion() GetRtceV1RtceTopicOKAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *GetRtceV1RtceTopicOK) GetKind() GetRtceV1RtceTopicOKKind {
	return s.Kind
}

// GetMetadata returns the value of Metadata.
func (s *GetRtceV1RtceTopicOK) GetMetadata() jx.Raw {
	return s.Metadata
}

// GetSpec returns the value of Spec.
func (s *GetRtceV1RtceTopicOK) GetSpec() GetRtceV1RtceTopicOKSpec {
	return s.Spec
}

// GetStatus returns the value of Status.
func (s *GetRtceV1RtceTopicOK) GetStatus() RtceV1RtceTopicStatus {
	return s.Status
}

// SetAPIVersion sets the value of APIVersion.
func (s *GetRtceV1RtceTopicOK) SetAPIVersion(val GetRtceV1RtceTopicOKAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *GetRtceV1RtceTopicOK) SetKind(val GetRtceV1RtceTopicOKKind) {
	s.Kind = val
}

// SetMetadata sets the value of Metadata.
func (s *GetRtceV1RtceTopicOK) SetMetadata(val jx.Raw) {
	s.Metadata = val
}

// SetSpec sets the value of Spec.
func (s *GetRtceV1RtceTopicOK) SetSpec(val GetRtceV1RtceTopicOKSpec) {
	s.Spec = val
}

// SetStatus sets the value of Status.
func (s *GetRtceV1RtceTopicOK) SetStatus(val RtceV1RtceTopicStatus) {
	s.Status = val
}

// APIVersion defines the schema version of this representation of a resource.
type GetRtceV1RtceTopicOKAPIVersion string

const (
	GetRtceV1RtceTopicOKAPIVersionRtceV1 GetRtceV1RtceTopicOKAPIVersion = "rtce/v1"
)

// AllValues returns all GetRtceV1RtceTopicOKAPIVersion values.
func (GetRtceV1RtceTopicOKAPIVersion) AllValues() []GetRtceV1RtceTopicOKAPIVersion {
	return []GetRtceV1RtceTopicOKAPIVersion{
		GetRtceV1RtceTopicOKAPIVersionRtceV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetRtceV1RtceTopicOKAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case GetRtceV1RtceTopicOKAPIVersionRtceV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetRtceV1RtceTopicOKAPIVersion) UnmarshalText(data []byte) error {
	switch GetRtceV1RtceTopicOKAPIVersion(data) {
	case GetRtceV1RtceTopicOKAPIVersionRtceV1:
		*s = GetRtceV1RtceTopicOKAPIVersionRtceV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// GetRtceV1RtceTopicOKHeaders wraps GetRtceV1RtceTopicOK with response headers.
type GetRtceV1RtceTopicOKHeaders struct {
	XRateLimitLimit     OptInt
	XRateLimitRemaining OptInt
	XRateLimitReset     OptInt
	XRequestID          OptString
	Response            GetRtceV1RtceTopicOK
}

// GetXRateLimitLimit returns the value of XRateLimitLimit.
func (s *GetRtceV1RtceTopicOKHeaders) GetXRateLimitLimit() OptInt {
	return s.XRateLimitLimit
}

// GetXRateLimitRemaining returns the value of XRateLimitRemaining.
func (s *GetRtceV1RtceTopicOKHeaders) GetXRateLimitRemaining() OptInt {
	return s.XRateLimitRemaining
}

// GetXRateLimitReset returns the value of XRateLimitReset.
func (s *GetRtceV1RtceTopicOKHeaders) GetXRateLimitReset() OptInt {
	return s.XRateLimitReset
}

// GetXRequestID returns the value of XRequestID.
func (s *GetRtceV1RtceTopicOKHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *GetRtceV1RtceTopicOKHeaders) GetResponse() GetRtceV1RtceTopicOK {
	return s.Response
}

// SetXRateLimitLimit sets the value of XRateLimitLimit.
func (s *GetRtceV1RtceTopicOKHeaders) SetXRateLimitLimit(val OptInt) {
	s.XRateLimitLimit = val
}

// SetXRateLimitRemaining sets the value of XRateLimitRemaining.
func (s *GetRtceV1RtceTopicOKHeaders) SetXRateLimitRemaining(val OptInt) {
	s.XRateLimitRemaining = val
}

// SetXRateLimitReset sets the value of XRateLimitReset.
func (s *GetRtceV1RtceTopicOKHeaders) SetXRateLimitReset(val OptInt) {
	s.XRateLimitReset = val
}

// SetXRequestID sets the value of XRequestID.
func (s *GetRtceV1RtceTopicOKHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *GetRtceV1RtceTopicOKHeaders) SetResponse(val GetRtceV1RtceTopicOK) {
	s.Response = val
}

func (*GetRtceV1RtceTopicOKHeaders) getRtceV1RtceTopicRes() {}

// Kind defines the object this REST resource represents.
type GetRtceV1RtceTopicOKKind string

const (
	GetRtceV1RtceTopicOKKindRtceTopic GetRtceV1RtceTopicOKKind = "RtceTopic"
)

// AllValues returns all GetRtceV1RtceTopicOKKind values.
func (GetRtceV1RtceTopicOKKind) AllValues() []GetRtceV1RtceTopicOKKind {
	return []GetRtceV1RtceTopicOKKind{
		GetRtceV1RtceTopicOKKindRtceTopic,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetRtceV1RtceTopicOKKind) MarshalText() ([]byte, error) {
	switch s {
	case GetRtceV1RtceTopicOKKindRtceTopic:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetRtceV1RtceTopicOKKind) UnmarshalText(data []byte) error {
	switch GetRtceV1RtceTopicOKKind(data) {
	case GetRtceV1RtceTopicOKKindRtceTopic:
		*s = GetRtceV1RtceTopicOKKindRtceTopic
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type GetRtceV1RtceTopicOKSpec struct {
	// Merged property.
	Environment EnvScopedObjectReference `json:"environment"`
	// Merged property.
	KafkaCluster EnvScopedObjectReference `json:"kafka_cluster"`
	// The cloud provider where the RTCE topic is deployed.
	Cloud string `json:"cloud"`
	// The cloud region where the RTCE topic is deployed.
	Region string `json:"region"`
	// The Kafka topic name containing the data for the RTCE topic.
	TopicName string `json:"topic_name"`
	// A model-readable description of the RTCE topic.
	Description string `json:"description"`
}

// GetEnvironment returns the value of Environment.
func (s *GetRtceV1RtceTopicOKSpec) GetEnvironment() EnvScopedObjectReference {
	return s.Environment
}

// GetKafkaCluster returns the value of KafkaCluster.
func (s *GetRtceV1RtceTopicOKSpec) GetKafkaCluster() EnvScopedObjectReference {
	return s.KafkaCluster
}

// GetCloud returns the value of Cloud.
func (s *GetRtceV1RtceTopicOKSpec) GetCloud() string {
	return s.Cloud
}

// GetRegion returns the value of Region.
func (s *GetRtceV1RtceTopicOKSpec) GetRegion() string {
	return s.Region
}

// GetTopicName returns the value of TopicName.
func (s *GetRtceV1RtceTopicOKSpec) GetTopicName() string {
	return s.TopicName
}

// GetDescription returns the value of Description.
func (s *GetRtceV1RtceTopicOKSpec) GetDescription() string {
	return s.Description
}

// SetEnvironment sets the value of Environment.
func (s *GetRtceV1RtceTopicOKSpec) SetEnvironment(val EnvScopedObjectReference) {
	s.Environment = val
}

// SetKafkaCluster sets the value of KafkaCluster.
func (s *GetRtceV1RtceTopicOKSpec) SetKafkaCluster(val EnvScopedObjectReference) {
	s.KafkaCluster = val
}

// SetCloud sets the value of Cloud.
func (s *GetRtceV1RtceTopicOKSpec) SetCloud(val string) {
	s.Cloud = val
}

// SetRegion sets the value of Region.
func (s *GetRtceV1RtceTopicOKSpec) SetRegion(val string) {
	s.Region = val
}

// SetTopicName sets the value of TopicName.
func (s *GetRtceV1RtceTopicOKSpec) SetTopicName(val string) {
	s.TopicName = val
}

// SetDescription sets the value of Description.
func (s *GetRtceV1RtceTopicOKSpec) SetDescription(val string) {
	s.Description = val
}

// Merged schema.
type ListRtceV1RtceTopicsOK struct {
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion ListRtceV1RtceTopicsOKAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind     ListRtceV1RtceTopicsOKKind     `json:"kind"`
	Metadata ListRtceV1RtceTopicsOKMetadata `json:"metadata"`
	// Merged property.
	Data []ListRtceV1RtceTopicsOKDataItem `json:"data"`
}

// GetAPIVersion returns the value of APIVersion.
func (s *ListRtceV1RtceTopicsOK) GetAPIVersion() ListRtceV1RtceTopicsOKAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *ListRtceV1RtceTopicsOK) GetKind() ListRtceV1RtceTopicsOKKind {
	return s.Kind
}

// GetMetadata returns the value of Metadata.
func (s *ListRtceV1RtceTopicsOK) GetMetadata() ListRtceV1RtceTopicsOKMetadata {
	return s.Metadata
}

// GetData returns the value of Data.
func (s *ListRtceV1RtceTopicsOK) GetData() []ListRtceV1RtceTopicsOKDataItem {
	return s.Data
}

// SetAPIVersion sets the value of APIVersion.
func (s *ListRtceV1RtceTopicsOK) SetAPIVersion(val ListRtceV1RtceTopicsOKAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *ListRtceV1RtceTopicsOK) SetKind(val ListRtceV1RtceTopicsOKKind) {
	s.Kind = val
}

// SetMetadata sets the value of Metadata.
func (s *ListRtceV1RtceTopicsOK) SetMetadata(val ListRtceV1RtceTopicsOKMetadata) {
	s.Metadata = val
}

// SetData sets the value of Data.
func (s *ListRtceV1RtceTopicsOK) SetData(val []ListRtceV1RtceTopicsOKDataItem) {
	s.Data = val
}

// APIVersion defines the schema version of this representation of a resource.
type ListRtceV1RtceTopicsOKAPIVersion string

const (
	ListRtceV1RtceTopicsOKAPIVersionRtceV1 ListRtceV1RtceTopicsOKAPIVersion = "rtce/v1"
)

// AllValues returns all ListRtceV1RtceTopicsOKAPIVersion values.
func (ListRtceV1RtceTopicsOKAPIVersion) AllValues() []ListRtceV1RtceTopicsOKAPIVersion {
	return []ListRtceV1RtceTopicsOKAPIVersion{
		ListRtceV1RtceTopicsOKAPIVersionRtceV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListRtceV1RtceTopicsOKAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case ListRtceV1RtceTopicsOKAPIVersionRtceV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListRtceV1RtceTopicsOKAPIVersion) UnmarshalText(data []byte) error {
	switch ListRtceV1RtceTopicsOKAPIVersion(data) {
	case ListRtceV1RtceTopicsOKAPIVersionRtceV1:
		*s = ListRtceV1RtceTopicsOKAPIVersionRtceV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type ListRtceV1RtceTopicsOKDataItem struct {
	// Merged property.
	Spec ListRtceV1RtceTopicsOKDataItemSpec `json:"spec"`
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion OptListRtceV1RtceTopicsOKDataItemAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind     OptListRtceV1RtceTopicsOKDataItemKind `json:"kind"`
	Metadata jx.Raw                                `json:"metadata"`
	Status   RtceV1RtceTopicStatus                 `json:"status"`
}

// GetSpec returns the value of Spec.
func (s *ListRtceV1RtceTopicsOKDataItem) GetSpec() ListRtceV1RtceTopicsOKDataItemSpec {
	return s.Spec
}

// GetAPIVersion returns the value of APIVersion.
func (s *ListRtceV1RtceTopicsOKDataItem) GetAPIVersion() OptListRtceV1RtceTopicsOKDataItemAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *ListRtceV1RtceTopicsOKDataItem) GetKind() OptListRtceV1RtceTopicsOKDataItemKind {
	return s.Kind
}

// GetMetadata returns the value of Metadata.
func (s *ListRtceV1RtceTopicsOKDataItem) GetMetadata() jx.Raw {
	return s.Metadata
}

// GetStatus returns the value of Status.
func (s *ListRtceV1RtceTopicsOKDataItem) GetStatus() RtceV1RtceTopicStatus {
	return s.Status
}

// SetSpec sets the value of Spec.
func (s *ListRtceV1RtceTopicsOKDataItem) SetSpec(val ListRtceV1RtceTopicsOKDataItemSpec) {
	s.Spec = val
}

// SetAPIVersion sets the value of APIVersion.
func (s *ListRtceV1RtceTopicsOKDataItem) SetAPIVersion(val OptListRtceV1RtceTopicsOKDataItemAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *ListRtceV1RtceTopicsOKDataItem) SetKind(val OptListRtceV1RtceTopicsOKDataItemKind) {
	s.Kind = val
}

// SetMetadata sets the value of Metadata.
func (s *ListRtceV1RtceTopicsOKDataItem) SetMetadata(val jx.Raw) {
	s.Metadata = val
}

// SetStatus sets the value of Status.
func (s *ListRtceV1RtceTopicsOKDataItem) SetStatus(val RtceV1RtceTopicStatus) {
	s.Status = val
}

// APIVersion defines the schema version of this representation of a resource.
type ListRtceV1RtceTopicsOKDataItemAPIVersion string

const (
	ListRtceV1RtceTopicsOKDataItemAPIVersionRtceV1 ListRtceV1RtceTopicsOKDataItemAPIVersion = "rtce/v1"
)

// AllValues returns all ListRtceV1RtceTopicsOKDataItemAPIVersion values.
func (ListRtceV1RtceTopicsOKDataItemAPIVersion) AllValues() []ListRtceV1RtceTopicsOKDataItemAPIVersion {
	return []ListRtceV1RtceTopicsOKDataItemAPIVersion{
		ListRtceV1RtceTopicsOKDataItemAPIVersionRtceV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListRtceV1RtceTopicsOKDataItemAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case ListRtceV1RtceTopicsOKDataItemAPIVersionRtceV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListRtceV1RtceTopicsOKDataItemAPIVersion) UnmarshalText(data []byte) error {
	switch ListRtceV1RtceTopicsOKDataItemAPIVersion(data) {
	case ListRtceV1RtceTopicsOKDataItemAPIVersionRtceV1:
		*s = ListRtceV1RtceTopicsOKDataItemAPIVersionRtceV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Kind defines the object this REST resource represents.
type ListRtceV1RtceTopicsOKDataItemKind string

const (
	ListRtceV1RtceTopicsOKDataItemKindRtceTopic ListRtceV1RtceTopicsOKDataItemKind = "RtceTopic"
)

// AllValues returns all ListRtceV1RtceTopicsOKDataItemKind values.
func (ListRtceV1RtceTopicsOKDataItemKind) AllValues() []ListRtceV1RtceTopicsOKDataItemKind {
	return []ListRtceV1RtceTopicsOKDataItemKind{
		ListRtceV1RtceTopicsOKDataItemKindRtceTopic,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListRtceV1RtceTopicsOKDataItemKind) MarshalText() ([]byte, error) {
	switch s {
	case ListRtceV1RtceTopicsOKDataItemKindRtceTopic:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListRtceV1RtceTopicsOKDataItemKind) UnmarshalText(data []byte) error {
	switch ListRtceV1RtceTopicsOKDataItemKind(data) {
	case ListRtceV1RtceTopicsOKDataItemKindRtceTopic:
		*s = ListRtceV1RtceTopicsOKDataItemKindRtceTopic
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type ListRtceV1RtceTopicsOKDataItemSpec struct {
	// The cloud provider where the RTCE topic is deployed.
	Cloud string `json:"cloud"`
	// The cloud region where the RTCE topic is deployed.
	Region string `json:"region"`
	// The Kafka topic name containing the data for the RTCE topic.
	TopicName string `json:"topic_name"`
	// A model-readable description of the RTCE topic.
	Description string `json:"description"`
	// Merged property.
	Environment EnvScopedObjectReference `json:"environment"`
	// Merged property.
	KafkaCluster EnvScopedObjectReference `json:"kafka_cluster"`
}

// GetCloud returns the value of Cloud.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) GetCloud() string {
	return s.Cloud
}

// GetRegion returns the value of Region.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) GetRegion() string {
	return s.Region
}

// GetTopicName returns the value of TopicName.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) GetTopicName() string {
	return s.TopicName
}

// GetDescription returns the value of Description.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) GetDescription() string {
	return s.Description
}

// GetEnvironment returns the value of Environment.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) GetEnvironment() EnvScopedObjectReference {
	return s.Environment
}

// GetKafkaCluster returns the value of KafkaCluster.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) GetKafkaCluster() EnvScopedObjectReference {
	return s.KafkaCluster
}

// SetCloud sets the value of Cloud.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) SetCloud(val string) {
	s.Cloud = val
}

// SetRegion sets the value of Region.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) SetRegion(val string) {
	s.Region = val
}

// SetTopicName sets the value of TopicName.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) SetTopicName(val string) {
	s.TopicName = val
}

// SetDescription sets the value of Description.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) SetDescription(val string) {
	s.Description = val
}

// SetEnvironment sets the value of Environment.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) SetEnvironment(val EnvScopedObjectReference) {
	s.Environment = val
}

// SetKafkaCluster sets the value of KafkaCluster.
func (s *ListRtceV1RtceTopicsOKDataItemSpec) SetKafkaCluster(val EnvScopedObjectReference) {
	s.KafkaCluster = val
}

// ListRtceV1RtceTopicsOKHeaders wraps ListRtceV1RtceTopicsOK with response headers.
type ListRtceV1RtceTopicsOKHeaders struct {
	XRateLimitLimit     OptInt
	XRateLimitRemaining OptInt
	XRateLimitReset     OptInt
	XRequestID          OptString
	Response            ListRtceV1RtceTopicsOK
}

// GetXRateLimitLimit returns the value of XRateLimitLimit.
func (s *ListRtceV1RtceTopicsOKHeaders) GetXRateLimitLimit() OptInt {
	return s.XRateLimitLimit
}

// GetXRateLimitRemaining returns the value of XRateLimitRemaining.
func (s *ListRtceV1RtceTopicsOKHeaders) GetXRateLimitRemaining() OptInt {
	return s.XRateLimitRemaining
}

// GetXRateLimitReset returns the value of XRateLimitReset.
func (s *ListRtceV1RtceTopicsOKHeaders) GetXRateLimitReset() OptInt {
	return s.XRateLimitReset
}

// GetXRequestID returns the value of XRequestID.
func (s *ListRtceV1RtceTopicsOKHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *ListRtceV1RtceTopicsOKHeaders) GetResponse() ListRtceV1RtceTopicsOK {
	return s.Response
}

// SetXRateLimitLimit sets the value of XRateLimitLimit.
func (s *ListRtceV1RtceTopicsOKHeaders) SetXRateLimitLimit(val OptInt) {
	s.XRateLimitLimit = val
}

// SetXRateLimitRemaining sets the value of XRateLimitRemaining.
func (s *ListRtceV1RtceTopicsOKHeaders) SetXRateLimitRemaining(val OptInt) {
	s.XRateLimitRemaining = val
}

// SetXRateLimitReset sets the value of XRateLimitReset.
func (s *ListRtceV1RtceTopicsOKHeaders) SetXRateLimitReset(val OptInt) {
	s.XRateLimitReset = val
}

// SetXRequestID sets the value of XRequestID.
func (s *ListRtceV1RtceTopicsOKHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *ListRtceV1RtceTopicsOKHeaders) SetResponse(val ListRtceV1RtceTopicsOK) {
	s.Response = val
}

func (*ListRtceV1RtceTopicsOKHeaders) listRtceV1RtceTopicsRes() {}

// Kind defines the object this REST resource represents.
type ListRtceV1RtceTopicsOKKind string

const (
	ListRtceV1RtceTopicsOKKindRtceTopicList ListRtceV1RtceTopicsOKKind = "RtceTopicList"
)

// AllValues returns all ListRtceV1RtceTopicsOKKind values.
func (ListRtceV1RtceTopicsOKKind) AllValues() []ListRtceV1RtceTopicsOKKind {
	return []ListRtceV1RtceTopicsOKKind{
		ListRtceV1RtceTopicsOKKindRtceTopicList,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListRtceV1RtceTopicsOKKind) MarshalText() ([]byte, error) {
	switch s {
	case ListRtceV1RtceTopicsOKKindRtceTopicList:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListRtceV1RtceTopicsOKKind) UnmarshalText(data []byte) error {
	switch ListRtceV1RtceTopicsOKKind(data) {
	case ListRtceV1RtceTopicsOKKindRtceTopicList:
		*s = ListRtceV1RtceTopicsOKKindRtceTopicList
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type ListRtceV1RtceTopicsOKMetadata struct {
	// Merged property.
	First OptNilURI `json:"first"`
	// Merged property.
	Last OptNilURI `json:"last"`
	// Merged property.
	Prev OptNilURI `json:"prev"`
	// Merged property.
	Next OptNilURI `json:"next"`
	// Number of records in the full result set. This response may be paginated and have a smaller number
	// of records.
	TotalSize OptInt32 `json:"total_size"`
}

// GetFirst returns the value of First.
func (s *ListRtceV1RtceTopicsOKMetadata) GetFirst() OptNilURI {
	return s.First
}

// GetLast returns the value of Last.
func (s *ListRtceV1RtceTopicsOKMetadata) GetLast() OptNilURI {
	return s.Last
}

// GetPrev returns the value of Prev.
func (s *ListRtceV1RtceTopicsOKMetadata) GetPrev() OptNilURI {
	return s.Prev
}

// GetNext returns the value of Next.
func (s *ListRtceV1RtceTopicsOKMetadata) GetNext() OptNilURI {
	return s.Next
}

// GetTotalSize returns the value of TotalSize.
func (s *ListRtceV1RtceTopicsOKMetadata) GetTotalSize() OptInt32 {
	return s.TotalSize
}

// SetFirst sets the value of First.
func (s *ListRtceV1RtceTopicsOKMetadata) SetFirst(val OptNilURI) {
	s.First = val
}

// SetLast sets the value of Last.
func (s *ListRtceV1RtceTopicsOKMetadata) SetLast(val OptNilURI) {
	s.Last = val
}

// SetPrev sets the value of Prev.
func (s *ListRtceV1RtceTopicsOKMetadata) SetPrev(val OptNilURI) {
	s.Prev = val
}

// SetNext sets the value of Next.
func (s *ListRtceV1RtceTopicsOKMetadata) SetNext(val OptNilURI) {
	s.Next = val
}

// SetTotalSize sets the value of TotalSize.
func (s *ListRtceV1RtceTopicsOKMetadata) SetTotalSize(val OptInt32) {
	s.TotalSize = val
}

// NotFoundErrorHeaders wraps Failure with response headers.
type NotFoundErrorHeaders struct {
	XRequestID OptString
	Response   Failure
}

// GetXRequestID returns the value of XRequestID.
func (s *NotFoundErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *NotFoundErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *NotFoundErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *NotFoundErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*NotFoundErrorHeaders) deleteRtceV1RtceTopicRes() {}
func (*NotFoundErrorHeaders) getRtceV1RtceTopicRes()    {}
func (*NotFoundErrorHeaders) updateRtceV1RtceTopicRes() {}

// NewOptCreateRtceV1RtceTopicAcceptedAPIVersion returns new OptCreateRtceV1RtceTopicAcceptedAPIVersion with value set to v.
func NewOptCreateRtceV1RtceTopicAcceptedAPIVersion(v CreateRtceV1RtceTopicAcceptedAPIVersion) OptCreateRtceV1RtceTopicAcceptedAPIVersion {
	return OptCreateRtceV1RtceTopicAcceptedAPIVersion{
		Value: v,
		Set:   true,
	}
}

// OptCreateRtceV1RtceTopicAcceptedAPIVersion is optional CreateRtceV1RtceTopicAcceptedAPIVersion.
type OptCreateRtceV1RtceTopicAcceptedAPIVersion struct {
	Value CreateRtceV1RtceTopicAcceptedAPIVersion
	Set   bool
}

// IsSet returns true if OptCreateRtceV1RtceTopicAcceptedAPIVersion was set.
func (o OptCreateRtceV1RtceTopicAcceptedAPIVersion) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateRtceV1RtceTopicAcceptedAPIVersion) Reset() {
	var v CreateRtceV1RtceTopicAcceptedAPIVersion
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateRtceV1RtceTopicAcceptedAPIVersion) SetTo(v CreateRtceV1RtceTopicAcceptedAPIVersion) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateRtceV1RtceTopicAcceptedAPIVersion) Get() (v CreateRtceV1RtceTopicAcceptedAPIVersion, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateRtceV1RtceTopicAcceptedAPIVersion) Or(d CreateRtceV1RtceTopicAcceptedAPIVersion) CreateRtceV1RtceTopicAcceptedAPIVersion {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateRtceV1RtceTopicAcceptedKind returns new OptCreateRtceV1RtceTopicAcceptedKind with value set to v.
func NewOptCreateRtceV1RtceTopicAcceptedKind(v CreateRtceV1RtceTopicAcceptedKind) OptCreateRtceV1RtceTopicAcceptedKind {
	return OptCreateRtceV1RtceTopicAcceptedKind{
		Value: v,
		Set:   true,
	}
}

// OptCreateRtceV1RtceTopicAcceptedKind is optional CreateRtceV1RtceTopicAcceptedKind.
type OptCreateRtceV1RtceTopicAcceptedKind struct {
	Value CreateRtceV1RtceTopicAcceptedKind
	Set   bool
}

// IsSet returns true if OptCreateRtceV1RtceTopicAcceptedKind was set.
func (o OptCreateRtceV1RtceTopicAcceptedKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateRtceV1RtceTopicAcceptedKind) Reset() {
	var v CreateRtceV1RtceTopicAcceptedKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateRtceV1RtceTopicAcceptedKind) SetTo(v CreateRtceV1RtceTopicAcceptedKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateRtceV1RtceTopicAcceptedKind) Get() (v CreateRtceV1RtceTopicAcceptedKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateRtceV1RtceTopicAcceptedKind) Or(d CreateRtceV1RtceTopicAcceptedKind) CreateRtceV1RtceTopicAcceptedKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateRtceV1RtceTopicReq returns new OptCreateRtceV1RtceTopicReq with value set to v.
func NewOptCreateRtceV1RtceTopicReq(v CreateRtceV1RtceTopicReq) OptCreateRtceV1RtceTopicReq {
	return OptCreateRtceV1RtceTopicReq{
		Value: v,
		Set:   true,
	}
}

// OptCreateRtceV1RtceTopicReq is optional CreateRtceV1RtceTopicReq.
type OptCreateRtceV1RtceTopicReq struct {
	Value CreateRtceV1RtceTopicReq
	Set   bool
}

// IsSet returns true if OptCreateRtceV1RtceTopicReq was set.
func (o OptCreateRtceV1RtceTopicReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateRtceV1RtceTopicReq) Reset() {
	var v CreateRtceV1RtceTopicReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateRtceV1RtceTopicReq) SetTo(v CreateRtceV1RtceTopicReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateRtceV1RtceTopicReq) Get() (v CreateRtceV1RtceTopicReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateRtceV1RtceTopicReq) Or(d CreateRtceV1RtceTopicReq) CreateRtceV1RtceTopicReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateRtceV1RtceTopicReqAPIVersion returns new OptCreateRtceV1RtceTopicReqAPIVersion with value set to v.
func NewOptCreateRtceV1RtceTopicReqAPIVersion(v CreateRtceV1RtceTopicReqAPIVersion) OptCreateRtceV1RtceTopicReqAPIVersion {
	return OptCreateRtceV1RtceTopicReqAPIVersion{
		Value: v,
		Set:   true,
	}
}

// OptCreateRtceV1RtceTopicReqAPIVersion is optional CreateRtceV1RtceTopicReqAPIVersion.
type OptCreateRtceV1RtceTopicReqAPIVersion struct {
	Value CreateRtceV1RtceTopicReqAPIVersion
	Set   bool
}

// IsSet returns true if OptCreateRtceV1RtceTopicReqAPIVersion was set.
func (o OptCreateRtceV1RtceTopicReqAPIVersion) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateRtceV1RtceTopicReqAPIVersion) Reset() {
	var v CreateRtceV1RtceTopicReqAPIVersion
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateRtceV1RtceTopicReqAPIVersion) SetTo(v CreateRtceV1RtceTopicReqAPIVersion) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateRtceV1RtceTopicReqAPIVersion) Get() (v CreateRtceV1RtceTopicReqAPIVersion, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateRtceV1RtceTopicReqAPIVersion) Or(d CreateRtceV1RtceTopicReqAPIVersion) CreateRtceV1RtceTopicReqAPIVersion {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateRtceV1RtceTopicReqKind returns new OptCreateRtceV1RtceTopicReqKind with value set to v.
func NewOptCreateRtceV1RtceTopicReqKind(v CreateRtceV1RtceTopicReqKind) OptCreateRtceV1RtceTopicReqKind {
	return OptCreateRtceV1RtceTopicReqKind{
		Value: v,
		Set:   true,
	}
}

// OptCreateRtceV1RtceTopicReqKind is optional CreateRtceV1RtceTopicReqKind.
type OptCreateRtceV1RtceTopicReqKind struct {
	Value CreateRtceV1RtceTopicReqKind
	Set   bool
}

// IsSet returns true if OptCreateRtceV1RtceTopicReqKind was set.
func (o OptCreateRtceV1RtceTopicReqKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateRtceV1RtceTopicReqKind) Reset() {
	var v CreateRtceV1RtceTopicReqKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateRtceV1RtceTopicReqKind) SetTo(v CreateRtceV1RtceTopicReqKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateRtceV1RtceTopicReqKind) Get() (v CreateRtceV1RtceTopicReqKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateRtceV1RtceTopicReqKind) Or(d CreateRtceV1RtceTopicReqKind) CreateRtceV1RtceTopicReqKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEnvScopedObjectReference returns new OptEnvScopedObjectReference with value set to v.
func NewOptEnvScopedObjectReference(v EnvScopedObjectReference) OptEnvScopedObjectReference {
	return OptEnvScopedObjectReference{
		Value: v,
		Set:   true,
	}
}

// OptEnvScopedObjectReference is optional EnvScopedObjectReference.
type OptEnvScopedObjectReference struct {
	Value EnvScopedObjectReference
	Set   bool
}

// IsSet returns true if OptEnvScopedObjectReference was set.
func (o OptEnvScopedObjectReference) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEnvScopedObjectReference) Reset() {
	var v EnvScopedObjectReference
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEnvScopedObjectReference) SetTo(v EnvScopedObjectReference) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEnvScopedObjectReference) Get() (v EnvScopedObjectReference, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEnvScopedObjectReference) Or(d EnvScopedObjectReference) EnvScopedObjectReference {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptErrorSource returns new OptErrorSource with value set to v.
func NewOptErrorSource(v ErrorSource) OptErrorSource {
	return OptErrorSource{
		Value: v,
		Set:   true,
	}
}

// OptErrorSource is optional ErrorSource.
type OptErrorSource struct {
	Value ErrorSource
	Set   bool
}

// IsSet returns true if OptErrorSource was set.
func (o OptErrorSource) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorSource) Reset() {
	var v ErrorSource
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorSource) SetTo(v ErrorSource) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorSource) Get() (v ErrorSource, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorSource) Or(d ErrorSource) ErrorSource {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListRtceV1RtceTopicsOKDataItemAPIVersion returns new OptListRtceV1RtceTopicsOKDataItemAPIVersion with value set to v.
func NewOptListRtceV1RtceTopicsOKDataItemAPIVersion(v ListRtceV1RtceTopicsOKDataItemAPIVersion) OptListRtceV1RtceTopicsOKDataItemAPIVersion {
	return OptListRtceV1RtceTopicsOKDataItemAPIVersion{
		Value: v,
		Set:   true,
	}
}

// OptListRtceV1RtceTopicsOKDataItemAPIVersion is optional ListRtceV1RtceTopicsOKDataItemAPIVersion.
type OptListRtceV1RtceTopicsOKDataItemAPIVersion struct {
	Value ListRtceV1RtceTopicsOKDataItemAPIVersion
	Set   bool
}

// IsSet returns true if OptListRtceV1RtceTopicsOKDataItemAPIVersion was set.
func (o OptListRtceV1RtceTopicsOKDataItemAPIVersion) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListRtceV1RtceTopicsOKDataItemAPIVersion) Reset() {
	var v ListRtceV1RtceTopicsOKDataItemAPIVersion
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListRtceV1RtceTopicsOKDataItemAPIVersion) SetTo(v ListRtceV1RtceTopicsOKDataItemAPIVersion) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListRtceV1RtceTopicsOKDataItemAPIVersion) Get() (v ListRtceV1RtceTopicsOKDataItemAPIVersion, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListRtceV1RtceTopicsOKDataItemAPIVersion) Or(d ListRtceV1RtceTopicsOKDataItemAPIVersion) ListRtceV1RtceTopicsOKDataItemAPIVersion {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListRtceV1RtceTopicsOKDataItemKind returns new OptListRtceV1RtceTopicsOKDataItemKind with value set to v.
func NewOptListRtceV1RtceTopicsOKDataItemKind(v ListRtceV1RtceTopicsOKDataItemKind) OptListRtceV1RtceTopicsOKDataItemKind {
	return OptListRtceV1RtceTopicsOKDataItemKind{
		Value: v,
		Set:   true,
	}
}

// OptListRtceV1RtceTopicsOKDataItemKind is optional ListRtceV1RtceTopicsOKDataItemKind.
type OptListRtceV1RtceTopicsOKDataItemKind struct {
	Value ListRtceV1RtceTopicsOKDataItemKind
	Set   bool
}

// IsSet returns true if OptListRtceV1RtceTopicsOKDataItemKind was set.
func (o OptListRtceV1RtceTopicsOKDataItemKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListRtceV1RtceTopicsOKDataItemKind) Reset() {
	var v ListRtceV1RtceTopicsOKDataItemKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListRtceV1RtceTopicsOKDataItemKind) SetTo(v ListRtceV1RtceTopicsOKDataItemKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListRtceV1RtceTopicsOKDataItemKind) Get() (v ListRtceV1RtceTopicsOKDataItemKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListRtceV1RtceTopicsOKDataItemKind) Or(d ListRtceV1RtceTopicsOKDataItemKind) ListRtceV1RtceTopicsOKDataItemKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilURI returns new OptNilURI with value set to v.
func NewOptNilURI(v url.URL) OptNilURI {
	return OptNilURI{
		Value: v,
		Set:   true,
	}
}

// OptNilURI is optional nullable url.URL.
type OptNilURI struct {
	Value url.URL
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilURI was set.
func (o OptNilURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilURI) SetTo(v url.URL) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilURI) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilURI) SetToNull() {
	o.Set = true
	o.Null = true
	var v url.URL
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilURI) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilURI) Get() (v url.URL, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRtceV1RtceTopicStatus returns new OptRtceV1RtceTopicStatus with value set to v.
func NewOptRtceV1RtceTopicStatus(v RtceV1RtceTopicStatus) OptRtceV1RtceTopicStatus {
	return OptRtceV1RtceTopicStatus{
		Value: v,
		Set:   true,
	}
}

// OptRtceV1RtceTopicStatus is optional RtceV1RtceTopicStatus.
type OptRtceV1RtceTopicStatus struct {
	Value RtceV1RtceTopicStatus
	Set   bool
}

// IsSet returns true if OptRtceV1RtceTopicStatus was set.
func (o OptRtceV1RtceTopicStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRtceV1RtceTopicStatus) Reset() {
	var v RtceV1RtceTopicStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRtceV1RtceTopicStatus) SetTo(v RtceV1RtceTopicStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRtceV1RtceTopicStatus) Get() (v RtceV1RtceTopicStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRtceV1RtceTopicStatus) Or(d RtceV1RtceTopicStatus) RtceV1RtceTopicStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSearchFilter returns new OptSearchFilter with value set to v.
func NewOptSearchFilter(v SearchFilter) OptSearchFilter {
	return OptSearchFilter{
		Value: v,
		Set:   true,
	}
}

// OptSearchFilter is optional SearchFilter.
type OptSearchFilter struct {
	Value SearchFilter
	Set   bool
}

// IsSet returns true if OptSearchFilter was set.
func (o OptSearchFilter) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSearchFilter) Reset() {
	var v SearchFilter
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSearchFilter) SetTo(v SearchFilter) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSearchFilter) Get() (v SearchFilter, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSearchFilter) Or(d SearchFilter) SearchFilter {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateRtceV1RtceTopicReq returns new OptUpdateRtceV1RtceTopicReq with value set to v.
func NewOptUpdateRtceV1RtceTopicReq(v UpdateRtceV1RtceTopicReq) OptUpdateRtceV1RtceTopicReq {
	return OptUpdateRtceV1RtceTopicReq{
		Value: v,
		Set:   true,
	}
}

// OptUpdateRtceV1RtceTopicReq is optional UpdateRtceV1RtceTopicReq.
type OptUpdateRtceV1RtceTopicReq struct {
	Value UpdateRtceV1RtceTopicReq
	Set   bool
}

// IsSet returns true if OptUpdateRtceV1RtceTopicReq was set.
func (o OptUpdateRtceV1RtceTopicReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateRtceV1RtceTopicReq) Reset() {
	var v UpdateRtceV1RtceTopicReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateRtceV1RtceTopicReq) SetTo(v UpdateRtceV1RtceTopicReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateRtceV1RtceTopicReq) Get() (v UpdateRtceV1RtceTopicReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateRtceV1RtceTopicReq) Or(d UpdateRtceV1RtceTopicReq) UpdateRtceV1RtceTopicReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateRtceV1RtceTopicReqAPIVersion returns new OptUpdateRtceV1RtceTopicReqAPIVersion with value set to v.
func NewOptUpdateRtceV1RtceTopicReqAPIVersion(v UpdateRtceV1RtceTopicReqAPIVersion) OptUpdateRtceV1RtceTopicReqAPIVersion {
	return OptUpdateRtceV1RtceTopicReqAPIVersion{
		Value: v,
		Set:   true,
	}
}

// OptUpdateRtceV1RtceTopicReqAPIVersion is optional UpdateRtceV1RtceTopicReqAPIVersion.
type OptUpdateRtceV1RtceTopicReqAPIVersion struct {
	Value UpdateRtceV1RtceTopicReqAPIVersion
	Set   bool
}

// IsSet returns true if OptUpdateRtceV1RtceTopicReqAPIVersion was set.
func (o OptUpdateRtceV1RtceTopicReqAPIVersion) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateRtceV1RtceTopicReqAPIVersion) Reset() {
	var v UpdateRtceV1RtceTopicReqAPIVersion
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateRtceV1RtceTopicReqAPIVersion) SetTo(v UpdateRtceV1RtceTopicReqAPIVersion) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateRtceV1RtceTopicReqAPIVersion) Get() (v UpdateRtceV1RtceTopicReqAPIVersion, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateRtceV1RtceTopicReqAPIVersion) Or(d UpdateRtceV1RtceTopicReqAPIVersion) UpdateRtceV1RtceTopicReqAPIVersion {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateRtceV1RtceTopicReqKind returns new OptUpdateRtceV1RtceTopicReqKind with value set to v.
func NewOptUpdateRtceV1RtceTopicReqKind(v UpdateRtceV1RtceTopicReqKind) OptUpdateRtceV1RtceTopicReqKind {
	return OptUpdateRtceV1RtceTopicReqKind{
		Value: v,
		Set:   true,
	}
}

// OptUpdateRtceV1RtceTopicReqKind is optional UpdateRtceV1RtceTopicReqKind.
type OptUpdateRtceV1RtceTopicReqKind struct {
	Value UpdateRtceV1RtceTopicReqKind
	Set   bool
}

// IsSet returns true if OptUpdateRtceV1RtceTopicReqKind was set.
func (o OptUpdateRtceV1RtceTopicReqKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateRtceV1RtceTopicReqKind) Reset() {
	var v UpdateRtceV1RtceTopicReqKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateRtceV1RtceTopicReqKind) SetTo(v UpdateRtceV1RtceTopicReqKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateRtceV1RtceTopicReqKind) Get() (v UpdateRtceV1RtceTopicReqKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateRtceV1RtceTopicReqKind) Or(d UpdateRtceV1RtceTopicReqKind) UpdateRtceV1RtceTopicReqKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/responses/RateLimitError
type RateLimitError struct {
	RetryAfter          OptInt
	XRateLimitLimit     OptInt
	XRateLimitRemaining OptInt
	XRateLimitReset     OptInt
	XRequestID          OptString
}

// GetRetryAfter returns the value of RetryAfter.
func (s *RateLimitError) GetRetryAfter() OptInt {
	return s.RetryAfter
}

// GetXRateLimitLimit returns the value of XRateLimitLimit.
func (s *RateLimitError) GetXRateLimitLimit() OptInt {
	return s.XRateLimitLimit
}

// GetXRateLimitRemaining returns the value of XRateLimitRemaining.
func (s *RateLimitError) GetXRateLimitRemaining() OptInt {
	return s.XRateLimitRemaining
}

// GetXRateLimitReset returns the value of XRateLimitReset.
func (s *RateLimitError) GetXRateLimitReset() OptInt {
	return s.XRateLimitReset
}

// GetXRequestID returns the value of XRequestID.
func (s *RateLimitError) GetXRequestID() OptString {
	return s.XRequestID
}

// SetRetryAfter sets the value of RetryAfter.
func (s *RateLimitError) SetRetryAfter(val OptInt) {
	s.RetryAfter = val
}

// SetXRateLimitLimit sets the value of XRateLimitLimit.
func (s *RateLimitError) SetXRateLimitLimit(val OptInt) {
	s.XRateLimitLimit = val
}

// SetXRateLimitRemaining sets the value of XRateLimitRemaining.
func (s *RateLimitError) SetXRateLimitRemaining(val OptInt) {
	s.XRateLimitRemaining = val
}

// SetXRateLimitReset sets the value of XRateLimitReset.
func (s *RateLimitError) SetXRateLimitReset(val OptInt) {
	s.XRateLimitReset = val
}

// SetXRequestID sets the value of XRequestID.
func (s *RateLimitError) SetXRequestID(val OptString) {
	s.XRequestID = val
}

func (*RateLimitError) createRtceV1RtceTopicRes() {}
func (*RateLimitError) deleteRtceV1RtceTopicRes() {}
func (*RateLimitError) getRtceV1RtceTopicRes()    {}
func (*RateLimitError) listRtceV1RtceTopicsRes()  {}
func (*RateLimitError) updateRtceV1RtceTopicRes() {}

type ResourceAPIKey struct {
	Username string
	Password string
	Roles    []string
}

// GetUsername returns the value of Username.
func (s *ResourceAPIKey) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *ResourceAPIKey) GetPassword() string {
	return s.Password
}

// GetRoles returns the value of Roles.
func (s *ResourceAPIKey) GetRoles() []string {
	return s.Roles
}

// SetUsername sets the value of Username.
func (s *ResourceAPIKey) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *ResourceAPIKey) SetPassword(val string) {
	s.Password = val
}

// SetRoles sets the value of Roles.
func (s *ResourceAPIKey) SetRoles(val []string) {
	s.Roles = val
}

// The status of the Rtce Topic.
// Ref: #/components/schemas/rtce.v1.RtceTopicStatus
type RtceV1RtceTopicStatus struct {
	// The lifecycle phase of the RtceTopic:
	//
	// PENDING: RtceTopic is pending initial validation;
	//
	// PROVISIONING: RtceTopic infrastructure is being provisioned;
	//
	// ACTIVE: RtceTopic is active and ready for use;
	//
	// DELETING: RtceTopic is being deleted;
	//
	// FAILED: RtceTopic provisioning failed;
	//
	// UNAVAILABLE: RtceTopic is temporarily unavailable.
	Phase string `json:"phase"`
	// Displayable error message if RtceTopic is in a failed state.
	ErrorMessage OptString `json:"error_message"`
}

// GetPhase returns the value of Phase.
func (s *RtceV1RtceTopicStatus) GetPhase() string {
	return s.Phase
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *RtceV1RtceTopicStatus) GetErrorMessage() OptString {
	return s.ErrorMessage
}

// SetPhase sets the value of Phase.
func (s *RtceV1RtceTopicStatus) SetPhase(val string) {
	s.Phase = val
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *RtceV1RtceTopicStatus) SetErrorMessage(val OptString) {
	s.ErrorMessage = val
}

type SearchFilter string

// UnauthenticatedErrorHeaders wraps Failure with response headers.
type UnauthenticatedErrorHeaders struct {
	WWWAuthenticate OptString
	XRequestID      OptString
	Response        Failure
}

// GetWWWAuthenticate returns the value of WWWAuthenticate.
func (s *UnauthenticatedErrorHeaders) GetWWWAuthenticate() OptString {
	return s.WWWAuthenticate
}

// GetXRequestID returns the value of XRequestID.
func (s *UnauthenticatedErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *UnauthenticatedErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetWWWAuthenticate sets the value of WWWAuthenticate.
func (s *UnauthenticatedErrorHeaders) SetWWWAuthenticate(val OptString) {
	s.WWWAuthenticate = val
}

// SetXRequestID sets the value of XRequestID.
func (s *UnauthenticatedErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnauthenticatedErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*UnauthenticatedErrorHeaders) createRtceV1RtceTopicRes() {}
func (*UnauthenticatedErrorHeaders) deleteRtceV1RtceTopicRes() {}
func (*UnauthenticatedErrorHeaders) getRtceV1RtceTopicRes()    {}
func (*UnauthenticatedErrorHeaders) listRtceV1RtceTopicsRes()  {}
func (*UnauthenticatedErrorHeaders) updateRtceV1RtceTopicRes() {}

// UnauthorizedErrorHeaders wraps Failure with response headers.
type UnauthorizedErrorHeaders struct {
	XRequestID OptString
	Response   Failure
}

// GetXRequestID returns the value of XRequestID.
func (s *UnauthorizedErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *UnauthorizedErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *UnauthorizedErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnauthorizedErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*UnauthorizedErrorHeaders) createRtceV1RtceTopicRes() {}
func (*UnauthorizedErrorHeaders) deleteRtceV1RtceTopicRes() {}
func (*UnauthorizedErrorHeaders) getRtceV1RtceTopicRes()    {}
func (*UnauthorizedErrorHeaders) listRtceV1RtceTopicsRes()  {}
func (*UnauthorizedErrorHeaders) updateRtceV1RtceTopicRes() {}

// Merged schema.
type UpdateRtceV1RtceTopicOK struct {
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion UpdateRtceV1RtceTopicOKAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind     UpdateRtceV1RtceTopicOKKind `json:"kind"`
	Metadata jx.Raw                      `json:"metadata"`
	// Merged property.
	Spec   UpdateRtceV1RtceTopicOKSpec `json:"spec"`
	Status RtceV1RtceTopicStatus       `json:"status"`
}

// GetAPIVersion returns the value of APIVersion.
func (s *UpdateRtceV1RtceTopicOK) GetAPIVersion() UpdateRtceV1RtceTopicOKAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *UpdateRtceV1RtceTopicOK) GetKind() UpdateRtceV1RtceTopicOKKind {
	return s.Kind
}

// GetMetadata returns the value of Metadata.
func (s *UpdateRtceV1RtceTopicOK) GetMetadata() jx.Raw {
	return s.Metadata
}

// GetSpec returns the value of Spec.
func (s *UpdateRtceV1RtceTopicOK) GetSpec() UpdateRtceV1RtceTopicOKSpec {
	return s.Spec
}

// GetStatus returns the value of Status.
func (s *UpdateRtceV1RtceTopicOK) GetStatus() RtceV1RtceTopicStatus {
	return s.Status
}

// SetAPIVersion sets the value of APIVersion.
func (s *UpdateRtceV1RtceTopicOK) SetAPIVersion(val UpdateRtceV1RtceTopicOKAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *UpdateRtceV1RtceTopicOK) SetKind(val UpdateRtceV1RtceTopicOKKind) {
	s.Kind = val
}

// SetMetadata sets the value of Metadata.
func (s *UpdateRtceV1RtceTopicOK) SetMetadata(val jx.Raw) {
	s.Metadata = val
}

// SetSpec sets the value of Spec.
func (s *UpdateRtceV1RtceTopicOK) SetSpec(val UpdateRtceV1RtceTopicOKSpec) {
	s.Spec = val
}

// SetStatus sets the value of Status.
func (s *UpdateRtceV1RtceTopicOK) SetStatus(val RtceV1RtceTopicStatus) {
	s.Status = val
}

// APIVersion defines the schema version of this representation of a resource.
type UpdateRtceV1RtceTopicOKAPIVersion string

const (
	UpdateRtceV1RtceTopicOKAPIVersionRtceV1 UpdateRtceV1RtceTopicOKAPIVersion = "rtce/v1"
)

// AllValues returns all UpdateRtceV1RtceTopicOKAPIVersion values.
func (UpdateRtceV1RtceTopicOKAPIVersion) AllValues() []UpdateRtceV1RtceTopicOKAPIVersion {
	return []UpdateRtceV1RtceTopicOKAPIVersion{
		UpdateRtceV1RtceTopicOKAPIVersionRtceV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateRtceV1RtceTopicOKAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case UpdateRtceV1RtceTopicOKAPIVersionRtceV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateRtceV1RtceTopicOKAPIVersion) UnmarshalText(data []byte) error {
	switch UpdateRtceV1RtceTopicOKAPIVersion(data) {
	case UpdateRtceV1RtceTopicOKAPIVersionRtceV1:
		*s = UpdateRtceV1RtceTopicOKAPIVersionRtceV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// UpdateRtceV1RtceTopicOKHeaders wraps UpdateRtceV1RtceTopicOK with response headers.
type UpdateRtceV1RtceTopicOKHeaders struct {
	XRateLimitLimit     OptInt
	XRateLimitRemaining OptInt
	XRateLimitReset     OptInt
	XRequestID          OptString
	Response            UpdateRtceV1RtceTopicOK
}

// GetXRateLimitLimit returns the value of XRateLimitLimit.
func (s *UpdateRtceV1RtceTopicOKHeaders) GetXRateLimitLimit() OptInt {
	return s.XRateLimitLimit
}

// GetXRateLimitRemaining returns the value of XRateLimitRemaining.
func (s *UpdateRtceV1RtceTopicOKHeaders) GetXRateLimitRemaining() OptInt {
	return s.XRateLimitRemaining
}

// GetXRateLimitReset returns the value of XRateLimitReset.
func (s *UpdateRtceV1RtceTopicOKHeaders) GetXRateLimitReset() OptInt {
	return s.XRateLimitReset
}

// GetXRequestID returns the value of XRequestID.
func (s *UpdateRtceV1RtceTopicOKHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *UpdateRtceV1RtceTopicOKHeaders) GetResponse() UpdateRtceV1RtceTopicOK {
	return s.Response
}

// SetXRateLimitLimit sets the value of XRateLimitLimit.
func (s *UpdateRtceV1RtceTopicOKHeaders) SetXRateLimitLimit(val OptInt) {
	s.XRateLimitLimit = val
}

// SetXRateLimitRemaining sets the value of XRateLimitRemaining.
func (s *UpdateRtceV1RtceTopicOKHeaders) SetXRateLimitRemaining(val OptInt) {
	s.XRateLimitRemaining = val
}

// SetXRateLimitReset sets the value of XRateLimitReset.
func (s *UpdateRtceV1RtceTopicOKHeaders) SetXRateLimitReset(val OptInt) {
	s.XRateLimitReset = val
}

// SetXRequestID sets the value of XRequestID.
func (s *UpdateRtceV1RtceTopicOKHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *UpdateRtceV1RtceTopicOKHeaders) SetResponse(val UpdateRtceV1RtceTopicOK) {
	s.Response = val
}

func (*UpdateRtceV1RtceTopicOKHeaders) updateRtceV1RtceTopicRes() {}

// Kind defines the object this REST resource represents.
type UpdateRtceV1RtceTopicOKKind string

const (
	UpdateRtceV1RtceTopicOKKindRtceTopic UpdateRtceV1RtceTopicOKKind = "RtceTopic"
)

// AllValues returns all UpdateRtceV1RtceTopicOKKind values.
func (UpdateRtceV1RtceTopicOKKind) AllValues() []UpdateRtceV1RtceTopicOKKind {
	return []UpdateRtceV1RtceTopicOKKind{
		UpdateRtceV1RtceTopicOKKindRtceTopic,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateRtceV1RtceTopicOKKind) MarshalText() ([]byte, error) {
	switch s {
	case UpdateRtceV1RtceTopicOKKindRtceTopic:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateRtceV1RtceTopicOKKind) UnmarshalText(data []byte) error {
	switch UpdateRtceV1RtceTopicOKKind(data) {
	case UpdateRtceV1RtceTopicOKKindRtceTopic:
		*s = UpdateRtceV1RtceTopicOKKindRtceTopic
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type UpdateRtceV1RtceTopicOKSpec struct {
	// Merged property.
	Environment EnvScopedObjectReference `json:"environment"`
	// Merged property.
	KafkaCluster EnvScopedObjectReference `json:"kafka_cluster"`
	// The cloud provider where the RTCE topic is deployed.
	Cloud string `json:"cloud"`
	// The cloud region where the RTCE topic is deployed.
	Region string `json:"region"`
	// The Kafka topic name containing the data for the RTCE topic.
	TopicName string `json:"topic_name"`
	// A model-readable description of the RTCE topic.
	Description string `json:"description"`
}

// GetEnvironment returns the value of Environment.
func (s *UpdateRtceV1RtceTopicOKSpec) GetEnvironment() EnvScopedObjectReference {
	return s.Environment
}

// GetKafkaCluster returns the value of KafkaCluster.
func (s *UpdateRtceV1RtceTopicOKSpec) GetKafkaCluster() EnvScopedObjectReference {
	return s.KafkaCluster
}

// GetCloud returns the value of Cloud.
func (s *UpdateRtceV1RtceTopicOKSpec) GetCloud() string {
	return s.Cloud
}

// GetRegion returns the value of Region.
func (s *UpdateRtceV1RtceTopicOKSpec) GetRegion() string {
	return s.Region
}

// GetTopicName returns the value of TopicName.
func (s *UpdateRtceV1RtceTopicOKSpec) GetTopicName() string {
	return s.TopicName
}

// GetDescription returns the value of Description.
func (s *UpdateRtceV1RtceTopicOKSpec) GetDescription() string {
	return s.Description
}

// SetEnvironment sets the value of Environment.
func (s *UpdateRtceV1RtceTopicOKSpec) SetEnvironment(val EnvScopedObjectReference) {
	s.Environment = val
}

// SetKafkaCluster sets the value of KafkaCluster.
func (s *UpdateRtceV1RtceTopicOKSpec) SetKafkaCluster(val EnvScopedObjectReference) {
	s.KafkaCluster = val
}

// SetCloud sets the value of Cloud.
func (s *UpdateRtceV1RtceTopicOKSpec) SetCloud(val string) {
	s.Cloud = val
}

// SetRegion sets the value of Region.
func (s *UpdateRtceV1RtceTopicOKSpec) SetRegion(val string) {
	s.Region = val
}

// SetTopicName sets the value of TopicName.
func (s *UpdateRtceV1RtceTopicOKSpec) SetTopicName(val string) {
	s.TopicName = val
}

// SetDescription sets the value of Description.
func (s *UpdateRtceV1RtceTopicOKSpec) SetDescription(val string) {
	s.Description = val
}

// Merged schema.
type UpdateRtceV1RtceTopicReq struct {
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion OptUpdateRtceV1RtceTopicReqAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind     OptUpdateRtceV1RtceTopicReqKind `json:"kind"`
	Metadata jx.Raw                          `json:"metadata"`
	// Merged property.
	Spec   UpdateRtceV1RtceTopicReqSpec `json:"spec"`
	Status OptRtceV1RtceTopicStatus     `json:"status"`
}

// GetAPIVersion returns the value of APIVersion.
func (s *UpdateRtceV1RtceTopicReq) GetAPIVersion() OptUpdateRtceV1RtceTopicReqAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *UpdateRtceV1RtceTopicReq) GetKind() OptUpdateRtceV1RtceTopicReqKind {
	return s.Kind
}

// GetMetadata returns the value of Metadata.
func (s *UpdateRtceV1RtceTopicReq) GetMetadata() jx.Raw {
	return s.Metadata
}

// GetSpec returns the value of Spec.
func (s *UpdateRtceV1RtceTopicReq) GetSpec() UpdateRtceV1RtceTopicReqSpec {
	return s.Spec
}

// GetStatus returns the value of Status.
func (s *UpdateRtceV1RtceTopicReq) GetStatus() OptRtceV1RtceTopicStatus {
	return s.Status
}

// SetAPIVersion sets the value of APIVersion.
func (s *UpdateRtceV1RtceTopicReq) SetAPIVersion(val OptUpdateRtceV1RtceTopicReqAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *UpdateRtceV1RtceTopicReq) SetKind(val OptUpdateRtceV1RtceTopicReqKind) {
	s.Kind = val
}

// SetMetadata sets the value of Metadata.
func (s *UpdateRtceV1RtceTopicReq) SetMetadata(val jx.Raw) {
	s.Metadata = val
}

// SetSpec sets the value of Spec.
func (s *UpdateRtceV1RtceTopicReq) SetSpec(val UpdateRtceV1RtceTopicReqSpec) {
	s.Spec = val
}

// SetStatus sets the value of Status.
func (s *UpdateRtceV1RtceTopicReq) SetStatus(val OptRtceV1RtceTopicStatus) {
	s.Status = val
}

// APIVersion defines the schema version of this representation of a resource.
type UpdateRtceV1RtceTopicReqAPIVersion string

const (
	UpdateRtceV1RtceTopicReqAPIVersionRtceV1 UpdateRtceV1RtceTopicReqAPIVersion = "rtce/v1"
)

// AllValues returns all UpdateRtceV1RtceTopicReqAPIVersion values.
func (UpdateRtceV1RtceTopicReqAPIVersion) AllValues() []UpdateRtceV1RtceTopicReqAPIVersion {
	return []UpdateRtceV1RtceTopicReqAPIVersion{
		UpdateRtceV1RtceTopicReqAPIVersionRtceV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateRtceV1RtceTopicReqAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case UpdateRtceV1RtceTopicReqAPIVersionRtceV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateRtceV1RtceTopicReqAPIVersion) UnmarshalText(data []byte) error {
	switch UpdateRtceV1RtceTopicReqAPIVersion(data) {
	case UpdateRtceV1RtceTopicReqAPIVersionRtceV1:
		*s = UpdateRtceV1RtceTopicReqAPIVersionRtceV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Kind defines the object this REST resource represents.
type UpdateRtceV1RtceTopicReqKind string

const (
	UpdateRtceV1RtceTopicReqKindRtceTopic UpdateRtceV1RtceTopicReqKind = "RtceTopic"
)

// AllValues returns all UpdateRtceV1RtceTopicReqKind values.
func (UpdateRtceV1RtceTopicReqKind) AllValues() []UpdateRtceV1RtceTopicReqKind {
	return []UpdateRtceV1RtceTopicReqKind{
		UpdateRtceV1RtceTopicReqKindRtceTopic,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateRtceV1RtceTopicReqKind) MarshalText() ([]byte, error) {
	switch s {
	case UpdateRtceV1RtceTopicReqKindRtceTopic:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateRtceV1RtceTopicReqKind) UnmarshalText(data []byte) error {
	switch UpdateRtceV1RtceTopicReqKind(data) {
	case UpdateRtceV1RtceTopicReqKindRtceTopic:
		*s = UpdateRtceV1RtceTopicReqKindRtceTopic
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type UpdateRtceV1RtceTopicReqSpec struct {
	// Merged property.
	Environment EnvScopedObjectReference `json:"environment"`
	// The cloud provider where the RTCE topic is deployed.
	Cloud OptString `json:"cloud"`
	// The cloud region where the RTCE topic is deployed.
	Region OptString `json:"region"`
	// The Kafka topic name containing the data for the RTCE topic.
	TopicName OptString `json:"topic_name"`
	// A model-readable description of the RTCE topic.
	Description OptString `json:"description"`
	// The Kafka cluster containing the topic to be materialized.
	KafkaCluster OptEnvScopedObjectReference `json:"kafka_cluster"`
}

// GetEnvironment returns the value of Environment.
func (s *UpdateRtceV1RtceTopicReqSpec) GetEnvironment() EnvScopedObjectReference {
	return s.Environment
}

// GetCloud returns the value of Cloud.
func (s *UpdateRtceV1RtceTopicReqSpec) GetCloud() OptString {
	return s.Cloud
}

// GetRegion returns the value of Region.
func (s *UpdateRtceV1RtceTopicReqSpec) GetRegion() OptString {
	return s.Region
}

// GetTopicName returns the value of TopicName.
func (s *UpdateRtceV1RtceTopicReqSpec) GetTopicName() OptString {
	return s.TopicName
}

// GetDescription returns the value of Description.
func (s *UpdateRtceV1RtceTopicReqSpec) GetDescription() OptString {
	return s.Description
}

// GetKafkaCluster returns the value of KafkaCluster.
func (s *UpdateRtceV1RtceTopicReqSpec) GetKafkaCluster() OptEnvScopedObjectReference {
	return s.KafkaCluster
}

// SetEnvironment sets the value of Environment.
func (s *UpdateRtceV1RtceTopicReqSpec) SetEnvironment(val EnvScopedObjectReference) {
	s.Environment = val
}

// SetCloud sets the value of Cloud.
func (s *UpdateRtceV1RtceTopicReqSpec) SetCloud(val OptString) {
	s.Cloud = val
}

// SetRegion sets the value of Region.
func (s *UpdateRtceV1RtceTopicReqSpec) SetRegion(val OptString) {
	s.Region = val
}

// SetTopicName sets the value of TopicName.
func (s *UpdateRtceV1RtceTopicReqSpec) SetTopicName(val OptString) {
	s.TopicName = val
}

// SetDescription sets the value of Description.
func (s *UpdateRtceV1RtceTopicReqSpec) SetDescription(val OptString) {
	s.Description = val
}

// SetKafkaCluster sets the value of KafkaCluster.
func (s *UpdateRtceV1RtceTopicReqSpec) SetKafkaCluster(val OptEnvScopedObjectReference) {
	s.KafkaCluster = val
}

// ValidationErrorHeaders wraps Failure with response headers.
type ValidationErrorHeaders struct {
	XRequestID OptString
	Response   Failure
}

// GetXRequestID returns the value of XRequestID.
func (s *ValidationErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *ValidationErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *ValidationErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *ValidationErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*ValidationErrorHeaders) createRtceV1RtceTopicRes() {}
func (*ValidationErrorHeaders) updateRtceV1RtceTopicRes() {}
