// Code generated by ogen, DO NOT EDIT.

package rtce

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateRtceV1RtceTopicOperation OperationName = "CreateRtceV1RtceTopic"
	DeleteRtceV1RtceTopicOperation OperationName = "DeleteRtceV1RtceTopic"
	GetRtceV1RtceTopicOperation    OperationName = "GetRtceV1RtceTopic"
	ListRtceV1RtceTopicsOperation  OperationName = "ListRtceV1RtceTopics"
	UpdateRtceV1RtceTopicOperation OperationName = "UpdateRtceV1RtceTopic"
)
