// Code generated by ogen, DO NOT EDIT.

package flink

import (
	"github.com/ogen-go/ogen/validate"
	"reflect"
)

// Equal compares two FcpmV2ComputePoolStatus instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a FcpmV2ComputePoolStatus) Equal(b FcpmV2ComputePoolStatus, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "FcpmV2ComputePoolStatus",
		})
	}

	if !reflect.DeepEqual(a.Phase, b.Phase) {
		return false
	}
	if !reflect.DeepEqual(a.CurrentCfu, b.CurrentCfu) {
		return false
	}
	return true
}
