// Code generated by ogen, DO NOT EDIT.

package kafka

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ExternalAccessToken provides external-access-token security value.
	// Authenticate with Confluent API using this credentials (JSON Web Tokens) following OAuth 2.0.
	ExternalAccessToken(ctx context.Context, operationName OperationName) (ExternalAccessToken, error)
	// ResourceAPIKey provides resource-api-key security value.
	// Authenticate with resource-specific API Keys using HTTP Basic Auth. Treat the resource-specific API
	// Key ID as the username and resource-specific API Key Secret as the password.
	ResourceAPIKey(ctx context.Context, operationName OperationName) (ResourceAPIKey, error)
}

// oauth2ScopesExternalAccessToken is a private map storing OAuth2 scopes per operation.
var oauth2ScopesExternalAccessToken = map[string][]string{
	BatchCreateKafkaAclsOperation:                                     []string{},
	CreateKafkaAclsOperation:                                          []string{},
	CreateKafkaLinkOperation:                                          []string{},
	CreateKafkaMirrorTopicOperation:                                   []string{},
	CreateKafkaTopicOperation:                                         []string{},
	DeleteKafkaAclsOperation:                                          []string{},
	DeleteKafkaClusterConfigOperation:                                 []string{},
	DeleteKafkaGroupConfigOperation:                                   []string{},
	DeleteKafkaLinkOperation:                                          []string{},
	DeleteKafkaLinkConfigOperation:                                    []string{},
	DeleteKafkaShareGroupOperation:                                    []string{},
	DeleteKafkaTopicOperation:                                         []string{},
	DeleteKafkaTopicConfigOperation:                                   []string{},
	GetKafkaAclsOperation:                                             []string{},
	GetKafkaClusterOperation:                                          []string{},
	GetKafkaClusterConfigOperation:                                    []string{},
	GetKafkaConsumerOperation:                                         []string{},
	GetKafkaConsumerGroupOperation:                                    []string{},
	GetKafkaConsumerGroupLagSummaryOperation:                          []string{},
	GetKafkaConsumerLagOperation:                                      []string{},
	GetKafkaGroupConfigOperation:                                      []string{},
	GetKafkaLinkOperation:                                             []string{},
	GetKafkaLinkConfigsOperation:                                      []string{},
	GetKafkaPartitionOperation:                                        []string{},
	GetKafkaShareGroupOperation:                                       []string{},
	GetKafkaShareGroupConsumerOperation:                               []string{},
	GetKafkaStreamsGroupOperation:                                     []string{},
	GetKafkaStreamsGroupMemberOperation:                               []string{},
	GetKafkaStreamsGroupMemberAssignmentTaskPartitionsOperation:       []string{},
	GetKafkaStreamsGroupMemberAssignmentsOperation:                    []string{},
	GetKafkaStreamsGroupMemberTargetAssignmentTaskPartitionsOperation: []string{},
	GetKafkaStreamsGroupMemberTargetAssignmentsOperation:              []string{},
	GetKafkaStreamsGroupSubtopologyOperation:                          []string{},
	GetKafkaTopicOperation:                                            []string{},
	GetKafkaTopicConfigOperation:                                      []string{},
	ListKafkaAllTopicConfigsOperation:                                 []string{},
	ListKafkaClusterConfigsOperation:                                  []string{},
	ListKafkaConsumerGroupsOperation:                                  []string{},
	ListKafkaConsumerLagsOperation:                                    []string{},
	ListKafkaConsumersOperation:                                       []string{},
	ListKafkaDefaultTopicConfigsOperation:                             []string{},
	ListKafkaGroupConfigsOperation:                                    []string{},
	ListKafkaLinkConfigsOperation:                                     []string{},
	ListKafkaLinksOperation:                                           []string{},
	ListKafkaMirrorTopicsOperation:                                    []string{},
	ListKafkaMirrorTopicsUnderLinkOperation:                           []string{},
	ListKafkaPartitionsOperation:                                      []string{},
	ListKafkaShareGroupConsumerAssignmentsOperation:                   []string{},
	ListKafkaShareGroupConsumersOperation:                             []string{},
	ListKafkaShareGroupsOperation:                                     []string{},
	ListKafkaStreamsGroupMemberAssignmentTasksOperation:               []string{},
	ListKafkaStreamsGroupMemberTargetAssignmentTasksOperation:         []string{},
	ListKafkaStreamsGroupMembersOperation:                             []string{},
	ListKafkaStreamsGroupSubtopologiesOperation:                       []string{},
	ListKafkaStreamsGroupsOperation:                                   []string{},
	ListKafkaTopicConfigsOperation:                                    []string{},
	ListKafkaTopicsOperation:                                          []string{},
	ProduceRecordOperation:                                            []string{},
	ReadKafkaMirrorTopicOperation:                                     []string{},
	UpdateKafkaClusterConfigOperation:                                 []string{},
	UpdateKafkaClusterConfigsOperation:                                []string{},
	UpdateKafkaGroupConfigOperation:                                   []string{},
	UpdateKafkaGroupConfigBatchOperation:                              []string{},
	UpdateKafkaLinkConfigOperation:                                    []string{},
	UpdateKafkaLinkConfigBatchOperation:                               []string{},
	UpdateKafkaMirrorTopicsFailoverOperation:                          []string{},
	UpdateKafkaMirrorTopicsPauseOperation:                             []string{},
	UpdateKafkaMirrorTopicsPromoteOperation:                           []string{},
	UpdateKafkaMirrorTopicsResumeOperation:                            []string{},
	UpdateKafkaMirrorTopicsReverseAndPauseMirrorOperation:             []string{},
	UpdateKafkaMirrorTopicsReverseAndStartMirrorOperation:             []string{},
	UpdateKafkaMirrorTopicsTruncateAndRestoreMirrorOperation:          []string{},
	UpdateKafkaTopicConfigOperation:                                   []string{},
	UpdateKafkaTopicConfigBatchOperation:                              []string{},
	UpdatePartitionCountKafkaTopicOperation:                           []string{},
}

// GetOAuth2ScopesForExternalAccessToken returns the required OAuth2 scopes for the given operation.
//
// This is useful for token exchange scenarios where you need to know which scopes
// to request when obtaining a token for a downstream API call.
//
// Example:
//
//	requiredScopes := GetOAuth2ScopesForExternalAccessToken(AddPetOperation)
//	token := exchangeTokenWithScopes(requiredScopes, "https://api.example.com")
//
// Returns nil if the operation has no scope requirements or if the operation is unknown.
func GetOAuth2ScopesForExternalAccessToken(operation string) []string {
	scopes, ok := oauth2ScopesExternalAccessToken[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(scopes))
	copy(result, scopes)
	return result
}

// operationRolesResourceAPIKey is a private map storing roles per operation.
var operationRolesResourceAPIKey = map[string][]string{
	BatchCreateKafkaAclsOperation:                                     []string{},
	CreateKafkaAclsOperation:                                          []string{},
	CreateKafkaLinkOperation:                                          []string{},
	CreateKafkaMirrorTopicOperation:                                   []string{},
	CreateKafkaTopicOperation:                                         []string{},
	DeleteKafkaAclsOperation:                                          []string{},
	DeleteKafkaClusterConfigOperation:                                 []string{},
	DeleteKafkaGroupConfigOperation:                                   []string{},
	DeleteKafkaLinkOperation:                                          []string{},
	DeleteKafkaLinkConfigOperation:                                    []string{},
	DeleteKafkaShareGroupOperation:                                    []string{},
	DeleteKafkaTopicOperation:                                         []string{},
	DeleteKafkaTopicConfigOperation:                                   []string{},
	GetKafkaAclsOperation:                                             []string{},
	GetKafkaClusterOperation:                                          []string{},
	GetKafkaClusterConfigOperation:                                    []string{},
	GetKafkaConsumerOperation:                                         []string{},
	GetKafkaConsumerGroupOperation:                                    []string{},
	GetKafkaConsumerGroupLagSummaryOperation:                          []string{},
	GetKafkaConsumerLagOperation:                                      []string{},
	GetKafkaGroupConfigOperation:                                      []string{},
	GetKafkaLinkOperation:                                             []string{},
	GetKafkaLinkConfigsOperation:                                      []string{},
	GetKafkaPartitionOperation:                                        []string{},
	GetKafkaShareGroupOperation:                                       []string{},
	GetKafkaShareGroupConsumerOperation:                               []string{},
	GetKafkaStreamsGroupOperation:                                     []string{},
	GetKafkaStreamsGroupMemberOperation:                               []string{},
	GetKafkaStreamsGroupMemberAssignmentTaskPartitionsOperation:       []string{},
	GetKafkaStreamsGroupMemberAssignmentsOperation:                    []string{},
	GetKafkaStreamsGroupMemberTargetAssignmentTaskPartitionsOperation: []string{},
	GetKafkaStreamsGroupMemberTargetAssignmentsOperation:              []string{},
	GetKafkaStreamsGroupSubtopologyOperation:                          []string{},
	GetKafkaTopicOperation:                                            []string{},
	GetKafkaTopicConfigOperation:                                      []string{},
	ListKafkaAllTopicConfigsOperation:                                 []string{},
	ListKafkaClusterConfigsOperation:                                  []string{},
	ListKafkaConsumerGroupsOperation:                                  []string{},
	ListKafkaConsumerLagsOperation:                                    []string{},
	ListKafkaConsumersOperation:                                       []string{},
	ListKafkaDefaultTopicConfigsOperation:                             []string{},
	ListKafkaGroupConfigsOperation:                                    []string{},
	ListKafkaLinkConfigsOperation:                                     []string{},
	ListKafkaLinksOperation:                                           []string{},
	ListKafkaMirrorTopicsOperation:                                    []string{},
	ListKafkaMirrorTopicsUnderLinkOperation:                           []string{},
	ListKafkaPartitionsOperation:                                      []string{},
	ListKafkaShareGroupConsumerAssignmentsOperation:                   []string{},
	ListKafkaShareGroupConsumersOperation:                             []string{},
	ListKafkaShareGroupsOperation:                                     []string{},
	ListKafkaStreamsGroupMemberAssignmentTasksOperation:               []string{},
	ListKafkaStreamsGroupMemberTargetAssignmentTasksOperation:         []string{},
	ListKafkaStreamsGroupMembersOperation:                             []string{},
	ListKafkaStreamsGroupSubtopologiesOperation:                       []string{},
	ListKafkaStreamsGroupsOperation:                                   []string{},
	ListKafkaTopicConfigsOperation:                                    []string{},
	ListKafkaTopicsOperation:                                          []string{},
	ProduceRecordOperation:                                            []string{},
	ReadKafkaMirrorTopicOperation:                                     []string{},
	UpdateKafkaClusterConfigOperation:                                 []string{},
	UpdateKafkaClusterConfigsOperation:                                []string{},
	UpdateKafkaGroupConfigOperation:                                   []string{},
	UpdateKafkaGroupConfigBatchOperation:                              []string{},
	UpdateKafkaLinkConfigOperation:                                    []string{},
	UpdateKafkaLinkConfigBatchOperation:                               []string{},
	UpdateKafkaMirrorTopicsFailoverOperation:                          []string{},
	UpdateKafkaMirrorTopicsPauseOperation:                             []string{},
	UpdateKafkaMirrorTopicsPromoteOperation:                           []string{},
	UpdateKafkaMirrorTopicsResumeOperation:                            []string{},
	UpdateKafkaMirrorTopicsReverseAndPauseMirrorOperation:             []string{},
	UpdateKafkaMirrorTopicsReverseAndStartMirrorOperation:             []string{},
	UpdateKafkaMirrorTopicsTruncateAndRestoreMirrorOperation:          []string{},
	UpdateKafkaTopicConfigOperation:                                   []string{},
	UpdateKafkaTopicConfigBatchOperation:                              []string{},
	UpdatePartitionCountKafkaTopicOperation:                           []string{},
}

// GetRolesForResourceAPIKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForResourceAPIKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForResourceAPIKey(operation string) []string {
	roles, ok := operationRolesResourceAPIKey[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityExternalAccessToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ExternalAccessToken(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ExternalAccessToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityResourceAPIKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ResourceAPIKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ResourceAPIKey\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
