// Code generated by ogen, DO NOT EDIT.

package service_quota

import (
	"net/url"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// BadRequestErrorHeaders wraps Failure with response headers.
type BadRequestErrorHeaders struct {
	XRequestID OptString
	Response   Failure
}

// GetXRequestID returns the value of XRequestID.
func (s *BadRequestErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *BadRequestErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *BadRequestErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *BadRequestErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*BadRequestErrorHeaders) getServiceQuotaV1AppliedQuotaRes()   {}
func (*BadRequestErrorHeaders) getServiceQuotaV1ScopeRes()          {}
func (*BadRequestErrorHeaders) listServiceQuotaV1AppliedQuotasRes() {}

type CloudAPIKey struct {
	Username string
	Password string
	Roles    []string
}

// GetUsername returns the value of Username.
func (s *CloudAPIKey) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *CloudAPIKey) GetPassword() string {
	return s.Password
}

// GetRoles returns the value of Roles.
func (s *CloudAPIKey) GetRoles() []string {
	return s.Roles
}

// SetUsername sets the value of Username.
func (s *CloudAPIKey) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *CloudAPIKey) SetPassword(val string) {
	s.Password = val
}

// SetRoles sets the value of Roles.
func (s *CloudAPIKey) SetRoles(val []string) {
	s.Roles = val
}

type ConfluentStsAccessToken struct {
	Token  string
	Scopes []string
}

// GetToken returns the value of Token.
func (s *ConfluentStsAccessToken) GetToken() string {
	return s.Token
}

// GetScopes returns the value of Scopes.
func (s *ConfluentStsAccessToken) GetScopes() []string {
	return s.Scopes
}

// SetToken sets the value of Token.
func (s *ConfluentStsAccessToken) SetToken(val string) {
	s.Token = val
}

// SetScopes sets the value of Scopes.
func (s *ConfluentStsAccessToken) SetScopes(val []string) {
	s.Scopes = val
}

// DefaultSystemErrorHeaders wraps Failure with response headers.
type DefaultSystemErrorHeaders struct {
	XRequestID OptString
	Response   Failure
}

// GetXRequestID returns the value of XRequestID.
func (s *DefaultSystemErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *DefaultSystemErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *DefaultSystemErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *DefaultSystemErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*DefaultSystemErrorHeaders) getServiceQuotaV1AppliedQuotaRes()   {}
func (*DefaultSystemErrorHeaders) getServiceQuotaV1ScopeRes()          {}
func (*DefaultSystemErrorHeaders) listServiceQuotaV1AppliedQuotasRes() {}

// Describes a particular error encountered while performing an operation.
// Ref: #/components/schemas/Error
type Error struct {
	// A unique identifier for this particular occurrence of the problem.
	ID OptString `json:"id"`
	// The HTTP status code applicable to this problem, expressed as a string value.
	Status OptString `json:"status"`
	// An application-specific error code, expressed as a string value.
	Code OptString `json:"code"`
	// A short, human-readable summary of the problem. It SHOULD NOT change from occurrence to occurrence
	// of the problem, except for purposes of localization.
	Title OptString `json:"title"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail OptString `json:"detail"`
	// If this error was caused by a particular part of the API request, the source will point to the query
	// string parameter or request body property that caused it.
	Source    OptErrorSource `json:"source"`
	ErrorCode OptInt32       `json:"error_code"`
	Message   OptNilString   `json:"message"`
}

// GetID returns the value of ID.
func (s *Error) GetID() OptString {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *Error) GetStatus() OptString {
	return s.Status
}

// GetCode returns the value of Code.
func (s *Error) GetCode() OptString {
	return s.Code
}

// GetTitle returns the value of Title.
func (s *Error) GetTitle() OptString {
	return s.Title
}

// GetDetail returns the value of Detail.
func (s *Error) GetDetail() OptString {
	return s.Detail
}

// GetSource returns the value of Source.
func (s *Error) GetSource() OptErrorSource {
	return s.Source
}

// GetErrorCode returns the value of ErrorCode.
func (s *Error) GetErrorCode() OptInt32 {
	return s.ErrorCode
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() OptNilString {
	return s.Message
}

// SetID sets the value of ID.
func (s *Error) SetID(val OptString) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *Error) SetStatus(val OptString) {
	s.Status = val
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val OptString) {
	s.Code = val
}

// SetTitle sets the value of Title.
func (s *Error) SetTitle(val OptString) {
	s.Title = val
}

// SetDetail sets the value of Detail.
func (s *Error) SetDetail(val OptString) {
	s.Detail = val
}

// SetSource sets the value of Source.
func (s *Error) SetSource(val OptErrorSource) {
	s.Source = val
}

// SetErrorCode sets the value of ErrorCode.
func (s *Error) SetErrorCode(val OptInt32) {
	s.ErrorCode = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val OptNilString) {
	s.Message = val
}

// If this error was caused by a particular part of the API request, the source will point to the query
// string parameter or request body property that caused it.
type ErrorSource struct {
	// A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/spec" for a spec
	// object, or "/spec/title" for a specific field].
	Pointer OptString `json:"pointer"`
	// A string indicating which query parameter caused the error.
	Parameter OptString `json:"parameter"`
}

// GetPointer returns the value of Pointer.
func (s *ErrorSource) GetPointer() OptString {
	return s.Pointer
}

// GetParameter returns the value of Parameter.
func (s *ErrorSource) GetParameter() OptString {
	return s.Parameter
}

// SetPointer sets the value of Pointer.
func (s *ErrorSource) SetPointer(val OptString) {
	s.Pointer = val
}

// SetParameter sets the value of Parameter.
func (s *ErrorSource) SetParameter(val OptString) {
	s.Parameter = val
}

// Provides information about problems encountered while performing an operation.
// Ref: #/components/schemas/Failure
type Failure struct {
	// List of errors which caused this operation to fail.
	Errors []Error `json:"errors"`
}

// GetErrors returns the value of Errors.
func (s *Failure) GetErrors() []Error {
	return s.Errors
}

// SetErrors sets the value of Errors.
func (s *Failure) SetErrors(val []Error) {
	s.Errors = val
}

// Merged schema.
type GetServiceQuotaV1AppliedQuotaOK struct {
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion GetServiceQuotaV1AppliedQuotaOKAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind GetServiceQuotaV1AppliedQuotaOKKind `json:"kind"`
	// ID is the "natural identifier" for an object within its scope/namespace; it is normally unique
	// across time but not space. That is, you can assume that the ID will not be reclaimed and reused
	// after an object is deleted ("time"); however, it may collide with IDs for other object `kinds` or
	// objects of the same `kind` within a different scope/namespace ("space").
	ID       string `json:"id"`
	Metadata jx.Raw `json:"metadata"`
	// The applied scope that this quota belongs to.
	Scope string `json:"scope"`
	// A human-readable name for the quota type name.
	DisplayName string `json:"display_name"`
	// The default service quota value.
	DefaultLimit int32 `json:"default_limit"`
	// The latest applied service quota value, taking into account any limit adjustments.
	AppliedLimit int32 `json:"applied_limit"`
	// Show the quota usage value if the quota usage is available for this quota.
	Usage OptInt32 `json:"usage"`
	// Merged property.
	User OptGlobalObjectReference `json:"user"`
	// Merged property.
	Organization OptNilGetServiceQuotaV1AppliedQuotaOKOrganization `json:"organization"`
	// Merged property.
	Environment OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment `json:"environment"`
	// Merged property.
	Network OptNilGetServiceQuotaV1AppliedQuotaOKNetwork `json:"network"`
	// Merged property.
	KafkaCluster OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster `json:"kafka_cluster"`
}

// GetAPIVersion returns the value of APIVersion.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetAPIVersion() GetServiceQuotaV1AppliedQuotaOKAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetKind() GetServiceQuotaV1AppliedQuotaOKKind {
	return s.Kind
}

// GetID returns the value of ID.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetID() string {
	return s.ID
}

// GetMetadata returns the value of Metadata.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetMetadata() jx.Raw {
	return s.Metadata
}

// GetScope returns the value of Scope.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetScope() string {
	return s.Scope
}

// GetDisplayName returns the value of DisplayName.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetDisplayName() string {
	return s.DisplayName
}

// GetDefaultLimit returns the value of DefaultLimit.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetDefaultLimit() int32 {
	return s.DefaultLimit
}

// GetAppliedLimit returns the value of AppliedLimit.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetAppliedLimit() int32 {
	return s.AppliedLimit
}

// GetUsage returns the value of Usage.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetUsage() OptInt32 {
	return s.Usage
}

// GetUser returns the value of User.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetUser() OptGlobalObjectReference {
	return s.User
}

// GetOrganization returns the value of Organization.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetOrganization() OptNilGetServiceQuotaV1AppliedQuotaOKOrganization {
	return s.Organization
}

// GetEnvironment returns the value of Environment.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetEnvironment() OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment {
	return s.Environment
}

// GetNetwork returns the value of Network.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetNetwork() OptNilGetServiceQuotaV1AppliedQuotaOKNetwork {
	return s.Network
}

// GetKafkaCluster returns the value of KafkaCluster.
func (s *GetServiceQuotaV1AppliedQuotaOK) GetKafkaCluster() OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster {
	return s.KafkaCluster
}

// SetAPIVersion sets the value of APIVersion.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetAPIVersion(val GetServiceQuotaV1AppliedQuotaOKAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetKind(val GetServiceQuotaV1AppliedQuotaOKKind) {
	s.Kind = val
}

// SetID sets the value of ID.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetID(val string) {
	s.ID = val
}

// SetMetadata sets the value of Metadata.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetMetadata(val jx.Raw) {
	s.Metadata = val
}

// SetScope sets the value of Scope.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetScope(val string) {
	s.Scope = val
}

// SetDisplayName sets the value of DisplayName.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetDefaultLimit sets the value of DefaultLimit.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetDefaultLimit(val int32) {
	s.DefaultLimit = val
}

// SetAppliedLimit sets the value of AppliedLimit.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetAppliedLimit(val int32) {
	s.AppliedLimit = val
}

// SetUsage sets the value of Usage.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetUsage(val OptInt32) {
	s.Usage = val
}

// SetUser sets the value of User.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetUser(val OptGlobalObjectReference) {
	s.User = val
}

// SetOrganization sets the value of Organization.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetOrganization(val OptNilGetServiceQuotaV1AppliedQuotaOKOrganization) {
	s.Organization = val
}

// SetEnvironment sets the value of Environment.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetEnvironment(val OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment) {
	s.Environment = val
}

// SetNetwork sets the value of Network.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetNetwork(val OptNilGetServiceQuotaV1AppliedQuotaOKNetwork) {
	s.Network = val
}

// SetKafkaCluster sets the value of KafkaCluster.
func (s *GetServiceQuotaV1AppliedQuotaOK) SetKafkaCluster(val OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster) {
	s.KafkaCluster = val
}

// APIVersion defines the schema version of this representation of a resource.
type GetServiceQuotaV1AppliedQuotaOKAPIVersion string

const (
	GetServiceQuotaV1AppliedQuotaOKAPIVersionServiceQuotaV1 GetServiceQuotaV1AppliedQuotaOKAPIVersion = "service-quota/v1"
)

// AllValues returns all GetServiceQuotaV1AppliedQuotaOKAPIVersion values.
func (GetServiceQuotaV1AppliedQuotaOKAPIVersion) AllValues() []GetServiceQuotaV1AppliedQuotaOKAPIVersion {
	return []GetServiceQuotaV1AppliedQuotaOKAPIVersion{
		GetServiceQuotaV1AppliedQuotaOKAPIVersionServiceQuotaV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetServiceQuotaV1AppliedQuotaOKAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case GetServiceQuotaV1AppliedQuotaOKAPIVersionServiceQuotaV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetServiceQuotaV1AppliedQuotaOKAPIVersion) UnmarshalText(data []byte) error {
	switch GetServiceQuotaV1AppliedQuotaOKAPIVersion(data) {
	case GetServiceQuotaV1AppliedQuotaOKAPIVersionServiceQuotaV1:
		*s = GetServiceQuotaV1AppliedQuotaOKAPIVersionServiceQuotaV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type GetServiceQuotaV1AppliedQuotaOKEnvironment struct {
	// ID of the referred resource.
	ID string `json:"id"`
	// API URL for accessing or modifying the referred object.
	Related url.URL `json:"related"`
	// CRN reference to the referred resource.
	ResourceName url.URL `json:"resource_name"`
}

// GetID returns the value of ID.
func (s *GetServiceQuotaV1AppliedQuotaOKEnvironment) GetID() string {
	return s.ID
}

// GetRelated returns the value of Related.
func (s *GetServiceQuotaV1AppliedQuotaOKEnvironment) GetRelated() url.URL {
	return s.Related
}

// GetResourceName returns the value of ResourceName.
func (s *GetServiceQuotaV1AppliedQuotaOKEnvironment) GetResourceName() url.URL {
	return s.ResourceName
}

// SetID sets the value of ID.
func (s *GetServiceQuotaV1AppliedQuotaOKEnvironment) SetID(val string) {
	s.ID = val
}

// SetRelated sets the value of Related.
func (s *GetServiceQuotaV1AppliedQuotaOKEnvironment) SetRelated(val url.URL) {
	s.Related = val
}

// SetResourceName sets the value of ResourceName.
func (s *GetServiceQuotaV1AppliedQuotaOKEnvironment) SetResourceName(val url.URL) {
	s.ResourceName = val
}

// GetServiceQuotaV1AppliedQuotaOKHeaders wraps GetServiceQuotaV1AppliedQuotaOK with response headers.
type GetServiceQuotaV1AppliedQuotaOKHeaders struct {
	XRateLimitLimit     OptInt
	XRateLimitRemaining OptInt
	XRateLimitReset     OptInt
	XRequestID          OptString
	Response            GetServiceQuotaV1AppliedQuotaOK
}

// GetXRateLimitLimit returns the value of XRateLimitLimit.
func (s *GetServiceQuotaV1AppliedQuotaOKHeaders) GetXRateLimitLimit() OptInt {
	return s.XRateLimitLimit
}

// GetXRateLimitRemaining returns the value of XRateLimitRemaining.
func (s *GetServiceQuotaV1AppliedQuotaOKHeaders) GetXRateLimitRemaining() OptInt {
	return s.XRateLimitRemaining
}

// GetXRateLimitReset returns the value of XRateLimitReset.
func (s *GetServiceQuotaV1AppliedQuotaOKHeaders) GetXRateLimitReset() OptInt {
	return s.XRateLimitReset
}

// GetXRequestID returns the value of XRequestID.
func (s *GetServiceQuotaV1AppliedQuotaOKHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *GetServiceQuotaV1AppliedQuotaOKHeaders) GetResponse() GetServiceQuotaV1AppliedQuotaOK {
	return s.Response
}

// SetXRateLimitLimit sets the value of XRateLimitLimit.
func (s *GetServiceQuotaV1AppliedQuotaOKHeaders) SetXRateLimitLimit(val OptInt) {
	s.XRateLimitLimit = val
}

// SetXRateLimitRemaining sets the value of XRateLimitRemaining.
func (s *GetServiceQuotaV1AppliedQuotaOKHeaders) SetXRateLimitRemaining(val OptInt) {
	s.XRateLimitRemaining = val
}

// SetXRateLimitReset sets the value of XRateLimitReset.
func (s *GetServiceQuotaV1AppliedQuotaOKHeaders) SetXRateLimitReset(val OptInt) {
	s.XRateLimitReset = val
}

// SetXRequestID sets the value of XRequestID.
func (s *GetServiceQuotaV1AppliedQuotaOKHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *GetServiceQuotaV1AppliedQuotaOKHeaders) SetResponse(val GetServiceQuotaV1AppliedQuotaOK) {
	s.Response = val
}

func (*GetServiceQuotaV1AppliedQuotaOKHeaders) getServiceQuotaV1AppliedQuotaRes() {}

// Merged schema.
type GetServiceQuotaV1AppliedQuotaOKKafkaCluster struct {
	// ID of the referred resource.
	ID string `json:"id"`
	// Environment of the referred resource, if env-scoped.
	Environment OptString `json:"environment"`
	// API URL for accessing or modifying the referred object.
	Related url.URL `json:"related"`
	// CRN reference to the referred resource.
	ResourceName url.URL `json:"resource_name"`
}

// GetID returns the value of ID.
func (s *GetServiceQuotaV1AppliedQuotaOKKafkaCluster) GetID() string {
	return s.ID
}

// GetEnvironment returns the value of Environment.
func (s *GetServiceQuotaV1AppliedQuotaOKKafkaCluster) GetEnvironment() OptString {
	return s.Environment
}

// GetRelated returns the value of Related.
func (s *GetServiceQuotaV1AppliedQuotaOKKafkaCluster) GetRelated() url.URL {
	return s.Related
}

// GetResourceName returns the value of ResourceName.
func (s *GetServiceQuotaV1AppliedQuotaOKKafkaCluster) GetResourceName() url.URL {
	return s.ResourceName
}

// SetID sets the value of ID.
func (s *GetServiceQuotaV1AppliedQuotaOKKafkaCluster) SetID(val string) {
	s.ID = val
}

// SetEnvironment sets the value of Environment.
func (s *GetServiceQuotaV1AppliedQuotaOKKafkaCluster) SetEnvironment(val OptString) {
	s.Environment = val
}

// SetRelated sets the value of Related.
func (s *GetServiceQuotaV1AppliedQuotaOKKafkaCluster) SetRelated(val url.URL) {
	s.Related = val
}

// SetResourceName sets the value of ResourceName.
func (s *GetServiceQuotaV1AppliedQuotaOKKafkaCluster) SetResourceName(val url.URL) {
	s.ResourceName = val
}

// Kind defines the object this REST resource represents.
type GetServiceQuotaV1AppliedQuotaOKKind string

const (
	GetServiceQuotaV1AppliedQuotaOKKindAppliedQuota GetServiceQuotaV1AppliedQuotaOKKind = "AppliedQuota"
)

// AllValues returns all GetServiceQuotaV1AppliedQuotaOKKind values.
func (GetServiceQuotaV1AppliedQuotaOKKind) AllValues() []GetServiceQuotaV1AppliedQuotaOKKind {
	return []GetServiceQuotaV1AppliedQuotaOKKind{
		GetServiceQuotaV1AppliedQuotaOKKindAppliedQuota,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetServiceQuotaV1AppliedQuotaOKKind) MarshalText() ([]byte, error) {
	switch s {
	case GetServiceQuotaV1AppliedQuotaOKKindAppliedQuota:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetServiceQuotaV1AppliedQuotaOKKind) UnmarshalText(data []byte) error {
	switch GetServiceQuotaV1AppliedQuotaOKKind(data) {
	case GetServiceQuotaV1AppliedQuotaOKKindAppliedQuota:
		*s = GetServiceQuotaV1AppliedQuotaOKKindAppliedQuota
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type GetServiceQuotaV1AppliedQuotaOKNetwork struct {
	// ID of the referred resource.
	ID string `json:"id"`
	// Environment of the referred resource, if env-scoped.
	Environment OptString `json:"environment"`
	// API URL for accessing or modifying the referred object.
	Related url.URL `json:"related"`
	// CRN reference to the referred resource.
	ResourceName url.URL `json:"resource_name"`
}

// GetID returns the value of ID.
func (s *GetServiceQuotaV1AppliedQuotaOKNetwork) GetID() string {
	return s.ID
}

// GetEnvironment returns the value of Environment.
func (s *GetServiceQuotaV1AppliedQuotaOKNetwork) GetEnvironment() OptString {
	return s.Environment
}

// GetRelated returns the value of Related.
func (s *GetServiceQuotaV1AppliedQuotaOKNetwork) GetRelated() url.URL {
	return s.Related
}

// GetResourceName returns the value of ResourceName.
func (s *GetServiceQuotaV1AppliedQuotaOKNetwork) GetResourceName() url.URL {
	return s.ResourceName
}

// SetID sets the value of ID.
func (s *GetServiceQuotaV1AppliedQuotaOKNetwork) SetID(val string) {
	s.ID = val
}

// SetEnvironment sets the value of Environment.
func (s *GetServiceQuotaV1AppliedQuotaOKNetwork) SetEnvironment(val OptString) {
	s.Environment = val
}

// SetRelated sets the value of Related.
func (s *GetServiceQuotaV1AppliedQuotaOKNetwork) SetRelated(val url.URL) {
	s.Related = val
}

// SetResourceName sets the value of ResourceName.
func (s *GetServiceQuotaV1AppliedQuotaOKNetwork) SetResourceName(val url.URL) {
	s.ResourceName = val
}

// Merged schema.
type GetServiceQuotaV1AppliedQuotaOKOrganization struct {
	// ID of the referred resource.
	ID string `json:"id"`
	// API URL for accessing or modifying the referred object.
	Related url.URL `json:"related"`
	// CRN reference to the referred resource.
	ResourceName url.URL `json:"resource_name"`
}

// GetID returns the value of ID.
func (s *GetServiceQuotaV1AppliedQuotaOKOrganization) GetID() string {
	return s.ID
}

// GetRelated returns the value of Related.
func (s *GetServiceQuotaV1AppliedQuotaOKOrganization) GetRelated() url.URL {
	return s.Related
}

// GetResourceName returns the value of ResourceName.
func (s *GetServiceQuotaV1AppliedQuotaOKOrganization) GetResourceName() url.URL {
	return s.ResourceName
}

// SetID sets the value of ID.
func (s *GetServiceQuotaV1AppliedQuotaOKOrganization) SetID(val string) {
	s.ID = val
}

// SetRelated sets the value of Related.
func (s *GetServiceQuotaV1AppliedQuotaOKOrganization) SetRelated(val url.URL) {
	s.Related = val
}

// SetResourceName sets the value of ResourceName.
func (s *GetServiceQuotaV1AppliedQuotaOKOrganization) SetResourceName(val url.URL) {
	s.ResourceName = val
}

// Merged schema.
type GetServiceQuotaV1ScopeOK struct {
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion GetServiceQuotaV1ScopeOKAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind GetServiceQuotaV1ScopeOKKind `json:"kind"`
	// ID is the "natural identifier" for an object within its scope/namespace; it is normally unique
	// across time but not space. That is, you can assume that the ID will not be reclaimed and reused
	// after an object is deleted ("time"); however, it may collide with IDs for other object `kinds` or
	// objects of the same `kind` within a different scope/namespace ("space").
	ID       string `json:"id"`
	Metadata jx.Raw `json:"metadata"`
	// The quota scope for listing quotas queries.
	Description string `json:"description"`
}

// GetAPIVersion returns the value of APIVersion.
func (s *GetServiceQuotaV1ScopeOK) GetAPIVersion() GetServiceQuotaV1ScopeOKAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *GetServiceQuotaV1ScopeOK) GetKind() GetServiceQuotaV1ScopeOKKind {
	return s.Kind
}

// GetID returns the value of ID.
func (s *GetServiceQuotaV1ScopeOK) GetID() string {
	return s.ID
}

// GetMetadata returns the value of Metadata.
func (s *GetServiceQuotaV1ScopeOK) GetMetadata() jx.Raw {
	return s.Metadata
}

// GetDescription returns the value of Description.
func (s *GetServiceQuotaV1ScopeOK) GetDescription() string {
	return s.Description
}

// SetAPIVersion sets the value of APIVersion.
func (s *GetServiceQuotaV1ScopeOK) SetAPIVersion(val GetServiceQuotaV1ScopeOKAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *GetServiceQuotaV1ScopeOK) SetKind(val GetServiceQuotaV1ScopeOKKind) {
	s.Kind = val
}

// SetID sets the value of ID.
func (s *GetServiceQuotaV1ScopeOK) SetID(val string) {
	s.ID = val
}

// SetMetadata sets the value of Metadata.
func (s *GetServiceQuotaV1ScopeOK) SetMetadata(val jx.Raw) {
	s.Metadata = val
}

// SetDescription sets the value of Description.
func (s *GetServiceQuotaV1ScopeOK) SetDescription(val string) {
	s.Description = val
}

// APIVersion defines the schema version of this representation of a resource.
type GetServiceQuotaV1ScopeOKAPIVersion string

const (
	GetServiceQuotaV1ScopeOKAPIVersionServiceQuotaV1 GetServiceQuotaV1ScopeOKAPIVersion = "service-quota/v1"
)

// AllValues returns all GetServiceQuotaV1ScopeOKAPIVersion values.
func (GetServiceQuotaV1ScopeOKAPIVersion) AllValues() []GetServiceQuotaV1ScopeOKAPIVersion {
	return []GetServiceQuotaV1ScopeOKAPIVersion{
		GetServiceQuotaV1ScopeOKAPIVersionServiceQuotaV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetServiceQuotaV1ScopeOKAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case GetServiceQuotaV1ScopeOKAPIVersionServiceQuotaV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetServiceQuotaV1ScopeOKAPIVersion) UnmarshalText(data []byte) error {
	switch GetServiceQuotaV1ScopeOKAPIVersion(data) {
	case GetServiceQuotaV1ScopeOKAPIVersionServiceQuotaV1:
		*s = GetServiceQuotaV1ScopeOKAPIVersionServiceQuotaV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// GetServiceQuotaV1ScopeOKHeaders wraps GetServiceQuotaV1ScopeOK with response headers.
type GetServiceQuotaV1ScopeOKHeaders struct {
	XRateLimitLimit     OptInt
	XRateLimitRemaining OptInt
	XRateLimitReset     OptInt
	XRequestID          OptString
	Response            GetServiceQuotaV1ScopeOK
}

// GetXRateLimitLimit returns the value of XRateLimitLimit.
func (s *GetServiceQuotaV1ScopeOKHeaders) GetXRateLimitLimit() OptInt {
	return s.XRateLimitLimit
}

// GetXRateLimitRemaining returns the value of XRateLimitRemaining.
func (s *GetServiceQuotaV1ScopeOKHeaders) GetXRateLimitRemaining() OptInt {
	return s.XRateLimitRemaining
}

// GetXRateLimitReset returns the value of XRateLimitReset.
func (s *GetServiceQuotaV1ScopeOKHeaders) GetXRateLimitReset() OptInt {
	return s.XRateLimitReset
}

// GetXRequestID returns the value of XRequestID.
func (s *GetServiceQuotaV1ScopeOKHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *GetServiceQuotaV1ScopeOKHeaders) GetResponse() GetServiceQuotaV1ScopeOK {
	return s.Response
}

// SetXRateLimitLimit sets the value of XRateLimitLimit.
func (s *GetServiceQuotaV1ScopeOKHeaders) SetXRateLimitLimit(val OptInt) {
	s.XRateLimitLimit = val
}

// SetXRateLimitRemaining sets the value of XRateLimitRemaining.
func (s *GetServiceQuotaV1ScopeOKHeaders) SetXRateLimitRemaining(val OptInt) {
	s.XRateLimitRemaining = val
}

// SetXRateLimitReset sets the value of XRateLimitReset.
func (s *GetServiceQuotaV1ScopeOKHeaders) SetXRateLimitReset(val OptInt) {
	s.XRateLimitReset = val
}

// SetXRequestID sets the value of XRequestID.
func (s *GetServiceQuotaV1ScopeOKHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *GetServiceQuotaV1ScopeOKHeaders) SetResponse(val GetServiceQuotaV1ScopeOK) {
	s.Response = val
}

func (*GetServiceQuotaV1ScopeOKHeaders) getServiceQuotaV1ScopeRes() {}

// Kind defines the object this REST resource represents.
type GetServiceQuotaV1ScopeOKKind string

const (
	GetServiceQuotaV1ScopeOKKindScope GetServiceQuotaV1ScopeOKKind = "Scope"
)

// AllValues returns all GetServiceQuotaV1ScopeOKKind values.
func (GetServiceQuotaV1ScopeOKKind) AllValues() []GetServiceQuotaV1ScopeOKKind {
	return []GetServiceQuotaV1ScopeOKKind{
		GetServiceQuotaV1ScopeOKKindScope,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetServiceQuotaV1ScopeOKKind) MarshalText() ([]byte, error) {
	switch s {
	case GetServiceQuotaV1ScopeOKKindScope:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetServiceQuotaV1ScopeOKKind) UnmarshalText(data []byte) error {
	switch GetServiceQuotaV1ScopeOKKind(data) {
	case GetServiceQuotaV1ScopeOKKindScope:
		*s = GetServiceQuotaV1ScopeOKKindScope
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ObjectReference provides information for you to locate the referred object.
// Ref: #/components/schemas/GlobalObjectReference
type GlobalObjectReference struct {
	// ID of the referred resource.
	ID string `json:"id"`
	// API URL for accessing or modifying the referred object.
	Related url.URL `json:"related"`
	// CRN reference to the referred resource.
	ResourceName url.URL `json:"resource_name"`
}

// GetID returns the value of ID.
func (s *GlobalObjectReference) GetID() string {
	return s.ID
}

// GetRelated returns the value of Related.
func (s *GlobalObjectReference) GetRelated() url.URL {
	return s.Related
}

// GetResourceName returns the value of ResourceName.
func (s *GlobalObjectReference) GetResourceName() url.URL {
	return s.ResourceName
}

// SetID sets the value of ID.
func (s *GlobalObjectReference) SetID(val string) {
	s.ID = val
}

// SetRelated sets the value of Related.
func (s *GlobalObjectReference) SetRelated(val url.URL) {
	s.Related = val
}

// SetResourceName sets the value of ResourceName.
func (s *GlobalObjectReference) SetResourceName(val url.URL) {
	s.ResourceName = val
}

// Merged schema.
type ListServiceQuotaV1AppliedQuotasOK struct {
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion ListServiceQuotaV1AppliedQuotasOKAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind     ListServiceQuotaV1AppliedQuotasOKKind     `json:"kind"`
	Metadata ListServiceQuotaV1AppliedQuotasOKMetadata `json:"metadata"`
	// Merged property.
	Data []ListServiceQuotaV1AppliedQuotasOKDataItem `json:"data"`
}

// GetAPIVersion returns the value of APIVersion.
func (s *ListServiceQuotaV1AppliedQuotasOK) GetAPIVersion() ListServiceQuotaV1AppliedQuotasOKAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *ListServiceQuotaV1AppliedQuotasOK) GetKind() ListServiceQuotaV1AppliedQuotasOKKind {
	return s.Kind
}

// GetMetadata returns the value of Metadata.
func (s *ListServiceQuotaV1AppliedQuotasOK) GetMetadata() ListServiceQuotaV1AppliedQuotasOKMetadata {
	return s.Metadata
}

// GetData returns the value of Data.
func (s *ListServiceQuotaV1AppliedQuotasOK) GetData() []ListServiceQuotaV1AppliedQuotasOKDataItem {
	return s.Data
}

// SetAPIVersion sets the value of APIVersion.
func (s *ListServiceQuotaV1AppliedQuotasOK) SetAPIVersion(val ListServiceQuotaV1AppliedQuotasOKAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *ListServiceQuotaV1AppliedQuotasOK) SetKind(val ListServiceQuotaV1AppliedQuotasOKKind) {
	s.Kind = val
}

// SetMetadata sets the value of Metadata.
func (s *ListServiceQuotaV1AppliedQuotasOK) SetMetadata(val ListServiceQuotaV1AppliedQuotasOKMetadata) {
	s.Metadata = val
}

// SetData sets the value of Data.
func (s *ListServiceQuotaV1AppliedQuotasOK) SetData(val []ListServiceQuotaV1AppliedQuotasOKDataItem) {
	s.Data = val
}

// APIVersion defines the schema version of this representation of a resource.
type ListServiceQuotaV1AppliedQuotasOKAPIVersion string

const (
	ListServiceQuotaV1AppliedQuotasOKAPIVersionServiceQuotaV1 ListServiceQuotaV1AppliedQuotasOKAPIVersion = "service-quota/v1"
)

// AllValues returns all ListServiceQuotaV1AppliedQuotasOKAPIVersion values.
func (ListServiceQuotaV1AppliedQuotasOKAPIVersion) AllValues() []ListServiceQuotaV1AppliedQuotasOKAPIVersion {
	return []ListServiceQuotaV1AppliedQuotasOKAPIVersion{
		ListServiceQuotaV1AppliedQuotasOKAPIVersionServiceQuotaV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListServiceQuotaV1AppliedQuotasOKAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case ListServiceQuotaV1AppliedQuotasOKAPIVersionServiceQuotaV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListServiceQuotaV1AppliedQuotasOKAPIVersion) UnmarshalText(data []byte) error {
	switch ListServiceQuotaV1AppliedQuotasOKAPIVersion(data) {
	case ListServiceQuotaV1AppliedQuotasOKAPIVersionServiceQuotaV1:
		*s = ListServiceQuotaV1AppliedQuotasOKAPIVersionServiceQuotaV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type ListServiceQuotaV1AppliedQuotasOKDataItem struct {
	// Merged property.
	User OptGlobalObjectReference `json:"user"`
	// Merged property.
	Organization OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization `json:"organization"`
	// Merged property.
	Environment OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment `json:"environment"`
	// Merged property.
	Network OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork `json:"network"`
	// Merged property.
	KafkaCluster OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster `json:"kafka_cluster"`
	// APIVersion defines the schema version of this representation of a resource.
	APIVersion OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion `json:"api_version"`
	// Kind defines the object this REST resource represents.
	Kind OptListServiceQuotaV1AppliedQuotasOKDataItemKind `json:"kind"`
	// ID is the "natural identifier" for an object within its scope/namespace; it is normally unique
	// across time but not space. That is, you can assume that the ID will not be reclaimed and reused
	// after an object is deleted ("time"); however, it may collide with IDs for other object `kinds` or
	// objects of the same `kind` within a different scope/namespace ("space").
	ID       string `json:"id"`
	Metadata jx.Raw `json:"metadata"`
	// The applied scope that this quota belongs to.
	Scope string `json:"scope"`
	// A human-readable name for the quota type name.
	DisplayName string `json:"display_name"`
	// The default service quota value.
	DefaultLimit int32 `json:"default_limit"`
	// The latest applied service quota value, taking into account any limit adjustments.
	AppliedLimit int32 `json:"applied_limit"`
	// Show the quota usage value if the quota usage is available for this quota.
	Usage OptInt32 `json:"usage"`
}

// GetUser returns the value of User.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetUser() OptGlobalObjectReference {
	return s.User
}

// GetOrganization returns the value of Organization.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetOrganization() OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization {
	return s.Organization
}

// GetEnvironment returns the value of Environment.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetEnvironment() OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment {
	return s.Environment
}

// GetNetwork returns the value of Network.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetNetwork() OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork {
	return s.Network
}

// GetKafkaCluster returns the value of KafkaCluster.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetKafkaCluster() OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster {
	return s.KafkaCluster
}

// GetAPIVersion returns the value of APIVersion.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetAPIVersion() OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion {
	return s.APIVersion
}

// GetKind returns the value of Kind.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetKind() OptListServiceQuotaV1AppliedQuotasOKDataItemKind {
	return s.Kind
}

// GetID returns the value of ID.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetID() string {
	return s.ID
}

// GetMetadata returns the value of Metadata.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetMetadata() jx.Raw {
	return s.Metadata
}

// GetScope returns the value of Scope.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetScope() string {
	return s.Scope
}

// GetDisplayName returns the value of DisplayName.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetDisplayName() string {
	return s.DisplayName
}

// GetDefaultLimit returns the value of DefaultLimit.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetDefaultLimit() int32 {
	return s.DefaultLimit
}

// GetAppliedLimit returns the value of AppliedLimit.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetAppliedLimit() int32 {
	return s.AppliedLimit
}

// GetUsage returns the value of Usage.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) GetUsage() OptInt32 {
	return s.Usage
}

// SetUser sets the value of User.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetUser(val OptGlobalObjectReference) {
	s.User = val
}

// SetOrganization sets the value of Organization.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetOrganization(val OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization) {
	s.Organization = val
}

// SetEnvironment sets the value of Environment.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetEnvironment(val OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) {
	s.Environment = val
}

// SetNetwork sets the value of Network.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetNetwork(val OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork) {
	s.Network = val
}

// SetKafkaCluster sets the value of KafkaCluster.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetKafkaCluster(val OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) {
	s.KafkaCluster = val
}

// SetAPIVersion sets the value of APIVersion.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetAPIVersion(val OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) {
	s.APIVersion = val
}

// SetKind sets the value of Kind.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetKind(val OptListServiceQuotaV1AppliedQuotasOKDataItemKind) {
	s.Kind = val
}

// SetID sets the value of ID.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetID(val string) {
	s.ID = val
}

// SetMetadata sets the value of Metadata.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetMetadata(val jx.Raw) {
	s.Metadata = val
}

// SetScope sets the value of Scope.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetScope(val string) {
	s.Scope = val
}

// SetDisplayName sets the value of DisplayName.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetDefaultLimit sets the value of DefaultLimit.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetDefaultLimit(val int32) {
	s.DefaultLimit = val
}

// SetAppliedLimit sets the value of AppliedLimit.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetAppliedLimit(val int32) {
	s.AppliedLimit = val
}

// SetUsage sets the value of Usage.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItem) SetUsage(val OptInt32) {
	s.Usage = val
}

// APIVersion defines the schema version of this representation of a resource.
type ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion string

const (
	ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersionServiceQuotaV1 ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion = "service-quota/v1"
)

// AllValues returns all ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion values.
func (ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) AllValues() []ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion {
	return []ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion{
		ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersionServiceQuotaV1,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) MarshalText() ([]byte, error) {
	switch s {
	case ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersionServiceQuotaV1:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) UnmarshalText(data []byte) error {
	switch ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion(data) {
	case ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersionServiceQuotaV1:
		*s = ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersionServiceQuotaV1
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment struct {
	// ID of the referred resource.
	ID string `json:"id"`
	// API URL for accessing or modifying the referred object.
	Related url.URL `json:"related"`
	// CRN reference to the referred resource.
	ResourceName url.URL `json:"resource_name"`
}

// GetID returns the value of ID.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) GetID() string {
	return s.ID
}

// GetRelated returns the value of Related.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) GetRelated() url.URL {
	return s.Related
}

// GetResourceName returns the value of ResourceName.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) GetResourceName() url.URL {
	return s.ResourceName
}

// SetID sets the value of ID.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) SetID(val string) {
	s.ID = val
}

// SetRelated sets the value of Related.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) SetRelated(val url.URL) {
	s.Related = val
}

// SetResourceName sets the value of ResourceName.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) SetResourceName(val url.URL) {
	s.ResourceName = val
}

// Merged schema.
type ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster struct {
	// ID of the referred resource.
	ID string `json:"id"`
	// Environment of the referred resource, if env-scoped.
	Environment OptString `json:"environment"`
	// API URL for accessing or modifying the referred object.
	Related url.URL `json:"related"`
	// CRN reference to the referred resource.
	ResourceName url.URL `json:"resource_name"`
}

// GetID returns the value of ID.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) GetID() string {
	return s.ID
}

// GetEnvironment returns the value of Environment.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) GetEnvironment() OptString {
	return s.Environment
}

// GetRelated returns the value of Related.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) GetRelated() url.URL {
	return s.Related
}

// GetResourceName returns the value of ResourceName.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) GetResourceName() url.URL {
	return s.ResourceName
}

// SetID sets the value of ID.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) SetID(val string) {
	s.ID = val
}

// SetEnvironment sets the value of Environment.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) SetEnvironment(val OptString) {
	s.Environment = val
}

// SetRelated sets the value of Related.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) SetRelated(val url.URL) {
	s.Related = val
}

// SetResourceName sets the value of ResourceName.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) SetResourceName(val url.URL) {
	s.ResourceName = val
}

// Kind defines the object this REST resource represents.
type ListServiceQuotaV1AppliedQuotasOKDataItemKind string

const (
	ListServiceQuotaV1AppliedQuotasOKDataItemKindAppliedQuota ListServiceQuotaV1AppliedQuotasOKDataItemKind = "AppliedQuota"
)

// AllValues returns all ListServiceQuotaV1AppliedQuotasOKDataItemKind values.
func (ListServiceQuotaV1AppliedQuotasOKDataItemKind) AllValues() []ListServiceQuotaV1AppliedQuotasOKDataItemKind {
	return []ListServiceQuotaV1AppliedQuotasOKDataItemKind{
		ListServiceQuotaV1AppliedQuotasOKDataItemKindAppliedQuota,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListServiceQuotaV1AppliedQuotasOKDataItemKind) MarshalText() ([]byte, error) {
	switch s {
	case ListServiceQuotaV1AppliedQuotasOKDataItemKindAppliedQuota:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemKind) UnmarshalText(data []byte) error {
	switch ListServiceQuotaV1AppliedQuotasOKDataItemKind(data) {
	case ListServiceQuotaV1AppliedQuotasOKDataItemKindAppliedQuota:
		*s = ListServiceQuotaV1AppliedQuotasOKDataItemKindAppliedQuota
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type ListServiceQuotaV1AppliedQuotasOKDataItemNetwork struct {
	// ID of the referred resource.
	ID string `json:"id"`
	// Environment of the referred resource, if env-scoped.
	Environment OptString `json:"environment"`
	// API URL for accessing or modifying the referred object.
	Related url.URL `json:"related"`
	// CRN reference to the referred resource.
	ResourceName url.URL `json:"resource_name"`
}

// GetID returns the value of ID.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) GetID() string {
	return s.ID
}

// GetEnvironment returns the value of Environment.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) GetEnvironment() OptString {
	return s.Environment
}

// GetRelated returns the value of Related.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) GetRelated() url.URL {
	return s.Related
}

// GetResourceName returns the value of ResourceName.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) GetResourceName() url.URL {
	return s.ResourceName
}

// SetID sets the value of ID.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) SetID(val string) {
	s.ID = val
}

// SetEnvironment sets the value of Environment.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) SetEnvironment(val OptString) {
	s.Environment = val
}

// SetRelated sets the value of Related.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) SetRelated(val url.URL) {
	s.Related = val
}

// SetResourceName sets the value of ResourceName.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) SetResourceName(val url.URL) {
	s.ResourceName = val
}

// Merged schema.
type ListServiceQuotaV1AppliedQuotasOKDataItemOrganization struct {
	// ID of the referred resource.
	ID string `json:"id"`
	// API URL for accessing or modifying the referred object.
	Related url.URL `json:"related"`
	// CRN reference to the referred resource.
	ResourceName url.URL `json:"resource_name"`
}

// GetID returns the value of ID.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemOrganization) GetID() string {
	return s.ID
}

// GetRelated returns the value of Related.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemOrganization) GetRelated() url.URL {
	return s.Related
}

// GetResourceName returns the value of ResourceName.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemOrganization) GetResourceName() url.URL {
	return s.ResourceName
}

// SetID sets the value of ID.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemOrganization) SetID(val string) {
	s.ID = val
}

// SetRelated sets the value of Related.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemOrganization) SetRelated(val url.URL) {
	s.Related = val
}

// SetResourceName sets the value of ResourceName.
func (s *ListServiceQuotaV1AppliedQuotasOKDataItemOrganization) SetResourceName(val url.URL) {
	s.ResourceName = val
}

// ListServiceQuotaV1AppliedQuotasOKHeaders wraps ListServiceQuotaV1AppliedQuotasOK with response headers.
type ListServiceQuotaV1AppliedQuotasOKHeaders struct {
	XRateLimitLimit     OptInt
	XRateLimitRemaining OptInt
	XRateLimitReset     OptInt
	XRequestID          OptString
	Response            ListServiceQuotaV1AppliedQuotasOK
}

// GetXRateLimitLimit returns the value of XRateLimitLimit.
func (s *ListServiceQuotaV1AppliedQuotasOKHeaders) GetXRateLimitLimit() OptInt {
	return s.XRateLimitLimit
}

// GetXRateLimitRemaining returns the value of XRateLimitRemaining.
func (s *ListServiceQuotaV1AppliedQuotasOKHeaders) GetXRateLimitRemaining() OptInt {
	return s.XRateLimitRemaining
}

// GetXRateLimitReset returns the value of XRateLimitReset.
func (s *ListServiceQuotaV1AppliedQuotasOKHeaders) GetXRateLimitReset() OptInt {
	return s.XRateLimitReset
}

// GetXRequestID returns the value of XRequestID.
func (s *ListServiceQuotaV1AppliedQuotasOKHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *ListServiceQuotaV1AppliedQuotasOKHeaders) GetResponse() ListServiceQuotaV1AppliedQuotasOK {
	return s.Response
}

// SetXRateLimitLimit sets the value of XRateLimitLimit.
func (s *ListServiceQuotaV1AppliedQuotasOKHeaders) SetXRateLimitLimit(val OptInt) {
	s.XRateLimitLimit = val
}

// SetXRateLimitRemaining sets the value of XRateLimitRemaining.
func (s *ListServiceQuotaV1AppliedQuotasOKHeaders) SetXRateLimitRemaining(val OptInt) {
	s.XRateLimitRemaining = val
}

// SetXRateLimitReset sets the value of XRateLimitReset.
func (s *ListServiceQuotaV1AppliedQuotasOKHeaders) SetXRateLimitReset(val OptInt) {
	s.XRateLimitReset = val
}

// SetXRequestID sets the value of XRequestID.
func (s *ListServiceQuotaV1AppliedQuotasOKHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *ListServiceQuotaV1AppliedQuotasOKHeaders) SetResponse(val ListServiceQuotaV1AppliedQuotasOK) {
	s.Response = val
}

func (*ListServiceQuotaV1AppliedQuotasOKHeaders) listServiceQuotaV1AppliedQuotasRes() {}

// Kind defines the object this REST resource represents.
type ListServiceQuotaV1AppliedQuotasOKKind string

const (
	ListServiceQuotaV1AppliedQuotasOKKindAppliedQuotaList ListServiceQuotaV1AppliedQuotasOKKind = "AppliedQuotaList"
)

// AllValues returns all ListServiceQuotaV1AppliedQuotasOKKind values.
func (ListServiceQuotaV1AppliedQuotasOKKind) AllValues() []ListServiceQuotaV1AppliedQuotasOKKind {
	return []ListServiceQuotaV1AppliedQuotasOKKind{
		ListServiceQuotaV1AppliedQuotasOKKindAppliedQuotaList,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ListServiceQuotaV1AppliedQuotasOKKind) MarshalText() ([]byte, error) {
	switch s {
	case ListServiceQuotaV1AppliedQuotasOKKindAppliedQuotaList:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ListServiceQuotaV1AppliedQuotasOKKind) UnmarshalText(data []byte) error {
	switch ListServiceQuotaV1AppliedQuotasOKKind(data) {
	case ListServiceQuotaV1AppliedQuotasOKKindAppliedQuotaList:
		*s = ListServiceQuotaV1AppliedQuotasOKKindAppliedQuotaList
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
type ListServiceQuotaV1AppliedQuotasOKMetadata struct {
	// Merged property.
	First OptNilURI `json:"first"`
	// Merged property.
	Last OptNilURI `json:"last"`
	// Merged property.
	Prev OptNilURI `json:"prev"`
	// Merged property.
	Next OptNilURI `json:"next"`
	// Number of records in the full result set. This response may be paginated and have a smaller number
	// of records.
	TotalSize OptInt32 `json:"total_size"`
}

// GetFirst returns the value of First.
func (s *ListServiceQuotaV1AppliedQuotasOKMetadata) GetFirst() OptNilURI {
	return s.First
}

// GetLast returns the value of Last.
func (s *ListServiceQuotaV1AppliedQuotasOKMetadata) GetLast() OptNilURI {
	return s.Last
}

// GetPrev returns the value of Prev.
func (s *ListServiceQuotaV1AppliedQuotasOKMetadata) GetPrev() OptNilURI {
	return s.Prev
}

// GetNext returns the value of Next.
func (s *ListServiceQuotaV1AppliedQuotasOKMetadata) GetNext() OptNilURI {
	return s.Next
}

// GetTotalSize returns the value of TotalSize.
func (s *ListServiceQuotaV1AppliedQuotasOKMetadata) GetTotalSize() OptInt32 {
	return s.TotalSize
}

// SetFirst sets the value of First.
func (s *ListServiceQuotaV1AppliedQuotasOKMetadata) SetFirst(val OptNilURI) {
	s.First = val
}

// SetLast sets the value of Last.
func (s *ListServiceQuotaV1AppliedQuotasOKMetadata) SetLast(val OptNilURI) {
	s.Last = val
}

// SetPrev sets the value of Prev.
func (s *ListServiceQuotaV1AppliedQuotasOKMetadata) SetPrev(val OptNilURI) {
	s.Prev = val
}

// SetNext sets the value of Next.
func (s *ListServiceQuotaV1AppliedQuotasOKMetadata) SetNext(val OptNilURI) {
	s.Next = val
}

// SetTotalSize sets the value of TotalSize.
func (s *ListServiceQuotaV1AppliedQuotasOKMetadata) SetTotalSize(val OptInt32) {
	s.TotalSize = val
}

// NotFoundErrorHeaders wraps Failure with response headers.
type NotFoundErrorHeaders struct {
	XRequestID OptString
	Response   Failure
}

// GetXRequestID returns the value of XRequestID.
func (s *NotFoundErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *NotFoundErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *NotFoundErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *NotFoundErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*NotFoundErrorHeaders) getServiceQuotaV1AppliedQuotaRes() {}
func (*NotFoundErrorHeaders) getServiceQuotaV1ScopeRes()        {}

// NewOptErrorSource returns new OptErrorSource with value set to v.
func NewOptErrorSource(v ErrorSource) OptErrorSource {
	return OptErrorSource{
		Value: v,
		Set:   true,
	}
}

// OptErrorSource is optional ErrorSource.
type OptErrorSource struct {
	Value ErrorSource
	Set   bool
}

// IsSet returns true if OptErrorSource was set.
func (o OptErrorSource) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorSource) Reset() {
	var v ErrorSource
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorSource) SetTo(v ErrorSource) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorSource) Get() (v ErrorSource, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorSource) Or(d ErrorSource) ErrorSource {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGlobalObjectReference returns new OptGlobalObjectReference with value set to v.
func NewOptGlobalObjectReference(v GlobalObjectReference) OptGlobalObjectReference {
	return OptGlobalObjectReference{
		Value: v,
		Set:   true,
	}
}

// OptGlobalObjectReference is optional GlobalObjectReference.
type OptGlobalObjectReference struct {
	Value GlobalObjectReference
	Set   bool
}

// IsSet returns true if OptGlobalObjectReference was set.
func (o OptGlobalObjectReference) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGlobalObjectReference) Reset() {
	var v GlobalObjectReference
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGlobalObjectReference) SetTo(v GlobalObjectReference) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGlobalObjectReference) Get() (v GlobalObjectReference, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGlobalObjectReference) Or(d GlobalObjectReference) GlobalObjectReference {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion returns new OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion with value set to v.
func NewOptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion(v ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion {
	return OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion{
		Value: v,
		Set:   true,
	}
}

// OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion is optional ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion.
type OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion struct {
	Value ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion
	Set   bool
}

// IsSet returns true if OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion was set.
func (o OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) Reset() {
	var v ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) SetTo(v ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) Get() (v ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) Or(d ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion) ListServiceQuotaV1AppliedQuotasOKDataItemAPIVersion {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptListServiceQuotaV1AppliedQuotasOKDataItemKind returns new OptListServiceQuotaV1AppliedQuotasOKDataItemKind with value set to v.
func NewOptListServiceQuotaV1AppliedQuotasOKDataItemKind(v ListServiceQuotaV1AppliedQuotasOKDataItemKind) OptListServiceQuotaV1AppliedQuotasOKDataItemKind {
	return OptListServiceQuotaV1AppliedQuotasOKDataItemKind{
		Value: v,
		Set:   true,
	}
}

// OptListServiceQuotaV1AppliedQuotasOKDataItemKind is optional ListServiceQuotaV1AppliedQuotasOKDataItemKind.
type OptListServiceQuotaV1AppliedQuotasOKDataItemKind struct {
	Value ListServiceQuotaV1AppliedQuotasOKDataItemKind
	Set   bool
}

// IsSet returns true if OptListServiceQuotaV1AppliedQuotasOKDataItemKind was set.
func (o OptListServiceQuotaV1AppliedQuotasOKDataItemKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptListServiceQuotaV1AppliedQuotasOKDataItemKind) Reset() {
	var v ListServiceQuotaV1AppliedQuotasOKDataItemKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptListServiceQuotaV1AppliedQuotasOKDataItemKind) SetTo(v ListServiceQuotaV1AppliedQuotasOKDataItemKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptListServiceQuotaV1AppliedQuotasOKDataItemKind) Get() (v ListServiceQuotaV1AppliedQuotasOKDataItemKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptListServiceQuotaV1AppliedQuotasOKDataItemKind) Or(d ListServiceQuotaV1AppliedQuotasOKDataItemKind) ListServiceQuotaV1AppliedQuotasOKDataItemKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilGetServiceQuotaV1AppliedQuotaOKEnvironment returns new OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment with value set to v.
func NewOptNilGetServiceQuotaV1AppliedQuotaOKEnvironment(v GetServiceQuotaV1AppliedQuotaOKEnvironment) OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment {
	return OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment{
		Value: v,
		Set:   true,
	}
}

// OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment is optional nullable GetServiceQuotaV1AppliedQuotaOKEnvironment.
type OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment struct {
	Value GetServiceQuotaV1AppliedQuotaOKEnvironment
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment was set.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment) Reset() {
	var v GetServiceQuotaV1AppliedQuotaOKEnvironment
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment) SetTo(v GetServiceQuotaV1AppliedQuotaOKEnvironment) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment) SetToNull() {
	o.Set = true
	o.Null = true
	var v GetServiceQuotaV1AppliedQuotaOKEnvironment
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment) Get() (v GetServiceQuotaV1AppliedQuotaOKEnvironment, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKEnvironment) Or(d GetServiceQuotaV1AppliedQuotaOKEnvironment) GetServiceQuotaV1AppliedQuotaOKEnvironment {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster returns new OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster with value set to v.
func NewOptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster(v GetServiceQuotaV1AppliedQuotaOKKafkaCluster) OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster {
	return OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster{
		Value: v,
		Set:   true,
	}
}

// OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster is optional nullable GetServiceQuotaV1AppliedQuotaOKKafkaCluster.
type OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster struct {
	Value GetServiceQuotaV1AppliedQuotaOKKafkaCluster
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster was set.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster) Reset() {
	var v GetServiceQuotaV1AppliedQuotaOKKafkaCluster
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster) SetTo(v GetServiceQuotaV1AppliedQuotaOKKafkaCluster) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster) SetToNull() {
	o.Set = true
	o.Null = true
	var v GetServiceQuotaV1AppliedQuotaOKKafkaCluster
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster) Get() (v GetServiceQuotaV1AppliedQuotaOKKafkaCluster, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKKafkaCluster) Or(d GetServiceQuotaV1AppliedQuotaOKKafkaCluster) GetServiceQuotaV1AppliedQuotaOKKafkaCluster {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilGetServiceQuotaV1AppliedQuotaOKNetwork returns new OptNilGetServiceQuotaV1AppliedQuotaOKNetwork with value set to v.
func NewOptNilGetServiceQuotaV1AppliedQuotaOKNetwork(v GetServiceQuotaV1AppliedQuotaOKNetwork) OptNilGetServiceQuotaV1AppliedQuotaOKNetwork {
	return OptNilGetServiceQuotaV1AppliedQuotaOKNetwork{
		Value: v,
		Set:   true,
	}
}

// OptNilGetServiceQuotaV1AppliedQuotaOKNetwork is optional nullable GetServiceQuotaV1AppliedQuotaOKNetwork.
type OptNilGetServiceQuotaV1AppliedQuotaOKNetwork struct {
	Value GetServiceQuotaV1AppliedQuotaOKNetwork
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilGetServiceQuotaV1AppliedQuotaOKNetwork was set.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKNetwork) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKNetwork) Reset() {
	var v GetServiceQuotaV1AppliedQuotaOKNetwork
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKNetwork) SetTo(v GetServiceQuotaV1AppliedQuotaOKNetwork) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKNetwork) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKNetwork) SetToNull() {
	o.Set = true
	o.Null = true
	var v GetServiceQuotaV1AppliedQuotaOKNetwork
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilGetServiceQuotaV1AppliedQuotaOKNetwork) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKNetwork) Get() (v GetServiceQuotaV1AppliedQuotaOKNetwork, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKNetwork) Or(d GetServiceQuotaV1AppliedQuotaOKNetwork) GetServiceQuotaV1AppliedQuotaOKNetwork {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilGetServiceQuotaV1AppliedQuotaOKOrganization returns new OptNilGetServiceQuotaV1AppliedQuotaOKOrganization with value set to v.
func NewOptNilGetServiceQuotaV1AppliedQuotaOKOrganization(v GetServiceQuotaV1AppliedQuotaOKOrganization) OptNilGetServiceQuotaV1AppliedQuotaOKOrganization {
	return OptNilGetServiceQuotaV1AppliedQuotaOKOrganization{
		Value: v,
		Set:   true,
	}
}

// OptNilGetServiceQuotaV1AppliedQuotaOKOrganization is optional nullable GetServiceQuotaV1AppliedQuotaOKOrganization.
type OptNilGetServiceQuotaV1AppliedQuotaOKOrganization struct {
	Value GetServiceQuotaV1AppliedQuotaOKOrganization
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilGetServiceQuotaV1AppliedQuotaOKOrganization was set.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKOrganization) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKOrganization) Reset() {
	var v GetServiceQuotaV1AppliedQuotaOKOrganization
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKOrganization) SetTo(v GetServiceQuotaV1AppliedQuotaOKOrganization) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKOrganization) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilGetServiceQuotaV1AppliedQuotaOKOrganization) SetToNull() {
	o.Set = true
	o.Null = true
	var v GetServiceQuotaV1AppliedQuotaOKOrganization
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilGetServiceQuotaV1AppliedQuotaOKOrganization) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKOrganization) Get() (v GetServiceQuotaV1AppliedQuotaOKOrganization, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilGetServiceQuotaV1AppliedQuotaOKOrganization) Or(d GetServiceQuotaV1AppliedQuotaOKOrganization) GetServiceQuotaV1AppliedQuotaOKOrganization {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment returns new OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment with value set to v.
func NewOptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment(v ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment {
	return OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment{
		Value: v,
		Set:   true,
	}
}

// OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment is optional nullable ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment.
type OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment struct {
	Value ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment was set.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) Reset() {
	var v ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) SetTo(v ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) SetToNull() {
	o.Set = true
	o.Null = true
	var v ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) Get() (v ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) Or(d ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment) ListServiceQuotaV1AppliedQuotasOKDataItemEnvironment {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster returns new OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster with value set to v.
func NewOptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster(v ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster {
	return OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster{
		Value: v,
		Set:   true,
	}
}

// OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster is optional nullable ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster.
type OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster struct {
	Value ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster was set.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) Reset() {
	var v ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) SetTo(v ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) SetToNull() {
	o.Set = true
	o.Null = true
	var v ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) Get() (v ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) Or(d ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster) ListServiceQuotaV1AppliedQuotasOKDataItemKafkaCluster {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork returns new OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork with value set to v.
func NewOptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork(v ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork {
	return OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork{
		Value: v,
		Set:   true,
	}
}

// OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork is optional nullable ListServiceQuotaV1AppliedQuotasOKDataItemNetwork.
type OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork struct {
	Value ListServiceQuotaV1AppliedQuotasOKDataItemNetwork
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork was set.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork) Reset() {
	var v ListServiceQuotaV1AppliedQuotasOKDataItemNetwork
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork) SetTo(v ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork) SetToNull() {
	o.Set = true
	o.Null = true
	var v ListServiceQuotaV1AppliedQuotasOKDataItemNetwork
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork) Get() (v ListServiceQuotaV1AppliedQuotasOKDataItemNetwork, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemNetwork) Or(d ListServiceQuotaV1AppliedQuotasOKDataItemNetwork) ListServiceQuotaV1AppliedQuotasOKDataItemNetwork {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization returns new OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization with value set to v.
func NewOptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization(v ListServiceQuotaV1AppliedQuotasOKDataItemOrganization) OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization {
	return OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization{
		Value: v,
		Set:   true,
	}
}

// OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization is optional nullable ListServiceQuotaV1AppliedQuotasOKDataItemOrganization.
type OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization struct {
	Value ListServiceQuotaV1AppliedQuotasOKDataItemOrganization
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization was set.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization) Reset() {
	var v ListServiceQuotaV1AppliedQuotasOKDataItemOrganization
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization) SetTo(v ListServiceQuotaV1AppliedQuotasOKDataItemOrganization) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization) SetToNull() {
	o.Set = true
	o.Null = true
	var v ListServiceQuotaV1AppliedQuotasOKDataItemOrganization
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization) Get() (v ListServiceQuotaV1AppliedQuotasOKDataItemOrganization, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilListServiceQuotaV1AppliedQuotasOKDataItemOrganization) Or(d ListServiceQuotaV1AppliedQuotasOKDataItemOrganization) ListServiceQuotaV1AppliedQuotasOKDataItemOrganization {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilURI returns new OptNilURI with value set to v.
func NewOptNilURI(v url.URL) OptNilURI {
	return OptNilURI{
		Value: v,
		Set:   true,
	}
}

// OptNilURI is optional nullable url.URL.
type OptNilURI struct {
	Value url.URL
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilURI was set.
func (o OptNilURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilURI) SetTo(v url.URL) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilURI) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilURI) SetToNull() {
	o.Set = true
	o.Null = true
	var v url.URL
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilURI) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilURI) Get() (v url.URL, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSearchFilter returns new OptSearchFilter with value set to v.
func NewOptSearchFilter(v SearchFilter) OptSearchFilter {
	return OptSearchFilter{
		Value: v,
		Set:   true,
	}
}

// OptSearchFilter is optional SearchFilter.
type OptSearchFilter struct {
	Value SearchFilter
	Set   bool
}

// IsSet returns true if OptSearchFilter was set.
func (o OptSearchFilter) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSearchFilter) Reset() {
	var v SearchFilter
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSearchFilter) SetTo(v SearchFilter) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSearchFilter) Get() (v SearchFilter, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSearchFilter) Or(d SearchFilter) SearchFilter {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/responses/RateLimitError
type RateLimitError struct {
	RetryAfter          OptInt
	XRateLimitLimit     OptInt
	XRateLimitRemaining OptInt
	XRateLimitReset     OptInt
	XRequestID          OptString
}

// GetRetryAfter returns the value of RetryAfter.
func (s *RateLimitError) GetRetryAfter() OptInt {
	return s.RetryAfter
}

// GetXRateLimitLimit returns the value of XRateLimitLimit.
func (s *RateLimitError) GetXRateLimitLimit() OptInt {
	return s.XRateLimitLimit
}

// GetXRateLimitRemaining returns the value of XRateLimitRemaining.
func (s *RateLimitError) GetXRateLimitRemaining() OptInt {
	return s.XRateLimitRemaining
}

// GetXRateLimitReset returns the value of XRateLimitReset.
func (s *RateLimitError) GetXRateLimitReset() OptInt {
	return s.XRateLimitReset
}

// GetXRequestID returns the value of XRequestID.
func (s *RateLimitError) GetXRequestID() OptString {
	return s.XRequestID
}

// SetRetryAfter sets the value of RetryAfter.
func (s *RateLimitError) SetRetryAfter(val OptInt) {
	s.RetryAfter = val
}

// SetXRateLimitLimit sets the value of XRateLimitLimit.
func (s *RateLimitError) SetXRateLimitLimit(val OptInt) {
	s.XRateLimitLimit = val
}

// SetXRateLimitRemaining sets the value of XRateLimitRemaining.
func (s *RateLimitError) SetXRateLimitRemaining(val OptInt) {
	s.XRateLimitRemaining = val
}

// SetXRateLimitReset sets the value of XRateLimitReset.
func (s *RateLimitError) SetXRateLimitReset(val OptInt) {
	s.XRateLimitReset = val
}

// SetXRequestID sets the value of XRequestID.
func (s *RateLimitError) SetXRequestID(val OptString) {
	s.XRequestID = val
}

func (*RateLimitError) getServiceQuotaV1AppliedQuotaRes()   {}
func (*RateLimitError) getServiceQuotaV1ScopeRes()          {}
func (*RateLimitError) listServiceQuotaV1AppliedQuotasRes() {}

type SearchFilter string

// UnauthenticatedErrorHeaders wraps Failure with response headers.
type UnauthenticatedErrorHeaders struct {
	WWWAuthenticate OptString
	XRequestID      OptString
	Response        Failure
}

// GetWWWAuthenticate returns the value of WWWAuthenticate.
func (s *UnauthenticatedErrorHeaders) GetWWWAuthenticate() OptString {
	return s.WWWAuthenticate
}

// GetXRequestID returns the value of XRequestID.
func (s *UnauthenticatedErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *UnauthenticatedErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetWWWAuthenticate sets the value of WWWAuthenticate.
func (s *UnauthenticatedErrorHeaders) SetWWWAuthenticate(val OptString) {
	s.WWWAuthenticate = val
}

// SetXRequestID sets the value of XRequestID.
func (s *UnauthenticatedErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnauthenticatedErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*UnauthenticatedErrorHeaders) getServiceQuotaV1AppliedQuotaRes()   {}
func (*UnauthenticatedErrorHeaders) getServiceQuotaV1ScopeRes()          {}
func (*UnauthenticatedErrorHeaders) listServiceQuotaV1AppliedQuotasRes() {}

// UnauthorizedErrorHeaders wraps Failure with response headers.
type UnauthorizedErrorHeaders struct {
	XRequestID OptString
	Response   Failure
}

// GetXRequestID returns the value of XRequestID.
func (s *UnauthorizedErrorHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *UnauthorizedErrorHeaders) GetResponse() Failure {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *UnauthorizedErrorHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *UnauthorizedErrorHeaders) SetResponse(val Failure) {
	s.Response = val
}

func (*UnauthorizedErrorHeaders) getServiceQuotaV1AppliedQuotaRes()   {}
func (*UnauthorizedErrorHeaders) getServiceQuotaV1ScopeRes()          {}
func (*UnauthorizedErrorHeaders) listServiceQuotaV1AppliedQuotasRes() {}
