// Code generated by ogen, DO NOT EDIT.

package cam

// CreateCamV1ConnectArtifactParams is parameters of createCamV1ConnectArtifact operation.
type CreateCamV1ConnectArtifactParams struct {
	// Scope the operation to the given spec.cloud.
	SpecCloud SearchFilter
	// Scope the operation to the given environment.
	Environment SearchFilter
}

// DeleteCamV1ConnectArtifactParams is parameters of deleteCamV1ConnectArtifact operation.
type DeleteCamV1ConnectArtifactParams struct {
	// Scope the operation to the given spec.cloud.
	SpecCloud SearchFilter
	// Scope the operation to the given environment.
	Environment SearchFilter
	// The unique identifier for the connect artifact.
	ID string
}

// GetCamV1ConnectArtifactParams is parameters of getCamV1ConnectArtifact operation.
type GetCamV1ConnectArtifactParams struct {
	// Scope the operation to the given spec.cloud.
	SpecCloud SearchFilter
	// Scope the operation to the given environment.
	Environment SearchFilter
	// The unique identifier for the connect artifact.
	ID string
}
