// Code generated by ogen, DO NOT EDIT.

package usm

import (
	"github.com/ogen-go/ogen/validate"
	"reflect"
)

// Equal compares two ListUsmV1ConnectClustersOKDataItem instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a ListUsmV1ConnectClustersOKDataItem) Equal(b ListUsmV1ConnectClustersOKDataItem, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "ListUsmV1ConnectClustersOKDataItem",
		})
	}

	// Compare nested object: Environment
	if !a.Environment.Equal(b.Environment, depth+1) {
		return false
	}
	// Compare optional field: APIVersion
	if a.APIVersion.Set != b.APIVersion.Set {
		return false
	}
	if a.APIVersion.Set {
		if a.APIVersion.Value != b.APIVersion.Value {
			return false
		}
	}
	// Compare optional field: Kind
	if a.Kind.Set != b.Kind.Set {
		return false
	}
	if a.Kind.Set {
		if a.Kind.Value != b.Kind.Value {
			return false
		}
	}
	if !reflect.DeepEqual(a.ID, b.ID) {
		return false
	}
	if !reflect.DeepEqual(a.ConfluentPlatformConnectClusterID, b.ConfluentPlatformConnectClusterID) {
		return false
	}
	if !reflect.DeepEqual(a.KafkaClusterID, b.KafkaClusterID) {
		return false
	}
	// Compare optional field: UsmKafkaClusterID
	if a.UsmKafkaClusterID.Set != b.UsmKafkaClusterID.Set {
		return false
	}
	if a.UsmKafkaClusterID.Set {
		if a.UsmKafkaClusterID.Value != b.UsmKafkaClusterID.Value {
			return false
		}
	}
	// Compare optional field: Cloud
	if a.Cloud.Set != b.Cloud.Set {
		return false
	}
	if a.Cloud.Set {
		if a.Cloud.Value != b.Cloud.Value {
			return false
		}
	}
	// Compare optional field: Region
	if a.Region.Set != b.Region.Set {
		return false
	}
	if a.Region.Set {
		if a.Region.Value != b.Region.Value {
			return false
		}
	}
	return true
}
