// Code generated by ogen, DO NOT EDIT.

package org

import (
	"context"
	"io"
	"net/url"
	"strings"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/uri"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.39.0"
	"go.opentelemetry.io/otel/trace"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CreateOrgV2Environment invokes createOrgV2Environment operation.
	//
	// [General Availability]
	//
	// Make a request to create an environment.
	//
	// [General Availability]: #section/Versioning/API-Lifecycle-Policy
	//
	// POST /org/v2/environments
	CreateOrgV2Environment(ctx context.Context, request OptCreateOrgV2EnvironmentReq) (CreateOrgV2EnvironmentRes, error)
	// CreateOrgV2ScimToken invokes createOrgV2ScimToken operation.
	//
	// [General Availability]
	//
	// Make a request to create a scim token.
	//
	// [General Availability]: #section/Versioning/API-Lifecycle-Policy
	//
	// POST /org/v2/scim-tokens
	CreateOrgV2ScimToken(ctx context.Context, request OptCreateOrgV2ScimTokenReq) (CreateOrgV2ScimTokenRes, error)
	// DeleteOrgV2Environment invokes deleteOrgV2Environment operation.
	//
	// [General Availability]
	//
	// Make a request to delete an environment.
	//
	// If successful, this request will also recursively delete all of the environment's associated
	// resources, including all Kafka clusters, connectors, etc.
	//
	// [General Availability]: #section/Versioning/API-Lifecycle-Policy
	//
	// DELETE /org/v2/environments/{id}
	DeleteOrgV2Environment(ctx context.Context, params DeleteOrgV2EnvironmentParams) (DeleteOrgV2EnvironmentRes, error)
	// DeleteOrgV2ScimToken invokes deleteOrgV2ScimToken operation.
	//
	// [General Availability]
	//
	// Make a request to delete a scim token.
	//
	// [General Availability]: #section/Versioning/API-Lifecycle-Policy
	//
	// DELETE /org/v2/scim-tokens/{id}
	DeleteOrgV2ScimToken(ctx context.Context, params DeleteOrgV2ScimTokenParams) (DeleteOrgV2ScimTokenRes, error)
	// GetOrgV2Environment invokes getOrgV2Environment operation.
	//
	// [General Availability]
	//
	// Make a request to read an environment.
	//
	// [General Availability]: #section/Versioning/API-Lifecycle-Policy
	//
	// GET /org/v2/environments/{id}
	GetOrgV2Environment(ctx context.Context, params GetOrgV2EnvironmentParams) (GetOrgV2EnvironmentRes, error)
	// GetOrgV2Organization invokes getOrgV2Organization operation.
	//
	// [General Availability]
	//
	// Make a request to read an organization.
	//
	// [General Availability]: #section/Versioning/API-Lifecycle-Policy
	//
	// GET /org/v2/organizations/{id}
	GetOrgV2Organization(ctx context.Context, params GetOrgV2OrganizationParams) (GetOrgV2OrganizationRes, error)
	// UpdateOrgV2Environment invokes updateOrgV2Environment operation.
	//
	// [General Availability]
	//
	// Make a request to update an environment.
	//
	// [General Availability]: #section/Versioning/API-Lifecycle-Policy
	//
	// PATCH /org/v2/environments/{id}
	UpdateOrgV2Environment(ctx context.Context, request OptOrgV2Environment, params UpdateOrgV2EnvironmentParams) (UpdateOrgV2EnvironmentRes, error)
	// UpdateOrgV2Organization invokes updateOrgV2Organization operation.
	//
	// [General Availability]
	//
	// Make a request to update an organization.
	//
	// [General Availability]: #section/Versioning/API-Lifecycle-Policy
	//
	// PATCH /org/v2/organizations/{id}
	UpdateOrgV2Organization(ctx context.Context, request OptOrgV2Organization, params UpdateOrgV2OrganizationParams) (UpdateOrgV2OrganizationRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CreateOrgV2Environment invokes createOrgV2Environment operation.
//
// [General Availability]
//
// Make a request to create an environment.
//
// [General Availability]: #section/Versioning/API-Lifecycle-Policy
//
// POST /org/v2/environments
func (c *Client) CreateOrgV2Environment(ctx context.Context, request OptCreateOrgV2EnvironmentReq) (CreateOrgV2EnvironmentRes, error) {
	res, err := c.sendCreateOrgV2Environment(ctx, request)
	return res, err
}

func (c *Client) sendCreateOrgV2Environment(ctx context.Context, request OptCreateOrgV2EnvironmentReq) (res CreateOrgV2EnvironmentRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("createOrgV2Environment"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/org/v2/environments"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CreateOrgV2EnvironmentOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/org/v2/environments"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateOrgV2EnvironmentRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:CloudAPIKey"
			switch err := c.securityCloudAPIKey(ctx, CreateOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"CloudAPIKey\"")
			}
		}
		{
			stage = "Security:GlobalAPIKey"
			switch err := c.securityGlobalAPIKey(ctx, CreateOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"GlobalAPIKey\"")
			}
		}
		{
			stage = "Security:ConfluentStsAccessToken"
			switch err := c.securityConfluentStsAccessToken(ctx, CreateOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 2
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"ConfluentStsAccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
				{0b00000010},
				{0b00000100},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeCreateOrgV2EnvironmentResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateOrgV2ScimToken invokes createOrgV2ScimToken operation.
//
// [General Availability]
//
// Make a request to create a scim token.
//
// [General Availability]: #section/Versioning/API-Lifecycle-Policy
//
// POST /org/v2/scim-tokens
func (c *Client) CreateOrgV2ScimToken(ctx context.Context, request OptCreateOrgV2ScimTokenReq) (CreateOrgV2ScimTokenRes, error) {
	res, err := c.sendCreateOrgV2ScimToken(ctx, request)
	return res, err
}

func (c *Client) sendCreateOrgV2ScimToken(ctx context.Context, request OptCreateOrgV2ScimTokenReq) (res CreateOrgV2ScimTokenRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("createOrgV2ScimToken"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/org/v2/scim-tokens"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CreateOrgV2ScimTokenOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/org/v2/scim-tokens"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateOrgV2ScimTokenRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:CloudAPIKey"
			switch err := c.securityCloudAPIKey(ctx, CreateOrgV2ScimTokenOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"CloudAPIKey\"")
			}
		}
		{
			stage = "Security:ConfluentStsAccessToken"
			switch err := c.securityConfluentStsAccessToken(ctx, CreateOrgV2ScimTokenOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"ConfluentStsAccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
				{0b00000010},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeCreateOrgV2ScimTokenResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteOrgV2Environment invokes deleteOrgV2Environment operation.
//
// [General Availability]
//
// Make a request to delete an environment.
//
// If successful, this request will also recursively delete all of the environment's associated
// resources, including all Kafka clusters, connectors, etc.
//
// [General Availability]: #section/Versioning/API-Lifecycle-Policy
//
// DELETE /org/v2/environments/{id}
func (c *Client) DeleteOrgV2Environment(ctx context.Context, params DeleteOrgV2EnvironmentParams) (DeleteOrgV2EnvironmentRes, error) {
	res, err := c.sendDeleteOrgV2Environment(ctx, params)
	return res, err
}

func (c *Client) sendDeleteOrgV2Environment(ctx context.Context, params DeleteOrgV2EnvironmentParams) (res DeleteOrgV2EnvironmentRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("deleteOrgV2Environment"),
		semconv.HTTPRequestMethodKey.String("DELETE"),
		semconv.URLTemplateKey.String("/org/v2/environments/{id}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, DeleteOrgV2EnvironmentOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/org/v2/environments/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:CloudAPIKey"
			switch err := c.securityCloudAPIKey(ctx, DeleteOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"CloudAPIKey\"")
			}
		}
		{
			stage = "Security:GlobalAPIKey"
			switch err := c.securityGlobalAPIKey(ctx, DeleteOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"GlobalAPIKey\"")
			}
		}
		{
			stage = "Security:ConfluentStsAccessToken"
			switch err := c.securityConfluentStsAccessToken(ctx, DeleteOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 2
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"ConfluentStsAccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
				{0b00000010},
				{0b00000100},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeDeleteOrgV2EnvironmentResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteOrgV2ScimToken invokes deleteOrgV2ScimToken operation.
//
// [General Availability]
//
// Make a request to delete a scim token.
//
// [General Availability]: #section/Versioning/API-Lifecycle-Policy
//
// DELETE /org/v2/scim-tokens/{id}
func (c *Client) DeleteOrgV2ScimToken(ctx context.Context, params DeleteOrgV2ScimTokenParams) (DeleteOrgV2ScimTokenRes, error) {
	res, err := c.sendDeleteOrgV2ScimToken(ctx, params)
	return res, err
}

func (c *Client) sendDeleteOrgV2ScimToken(ctx context.Context, params DeleteOrgV2ScimTokenParams) (res DeleteOrgV2ScimTokenRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("deleteOrgV2ScimToken"),
		semconv.HTTPRequestMethodKey.String("DELETE"),
		semconv.URLTemplateKey.String("/org/v2/scim-tokens/{id}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, DeleteOrgV2ScimTokenOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/org/v2/scim-tokens/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:CloudAPIKey"
			switch err := c.securityCloudAPIKey(ctx, DeleteOrgV2ScimTokenOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"CloudAPIKey\"")
			}
		}
		{
			stage = "Security:ConfluentStsAccessToken"
			switch err := c.securityConfluentStsAccessToken(ctx, DeleteOrgV2ScimTokenOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"ConfluentStsAccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
				{0b00000010},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeDeleteOrgV2ScimTokenResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetOrgV2Environment invokes getOrgV2Environment operation.
//
// [General Availability]
//
// Make a request to read an environment.
//
// [General Availability]: #section/Versioning/API-Lifecycle-Policy
//
// GET /org/v2/environments/{id}
func (c *Client) GetOrgV2Environment(ctx context.Context, params GetOrgV2EnvironmentParams) (GetOrgV2EnvironmentRes, error) {
	res, err := c.sendGetOrgV2Environment(ctx, params)
	return res, err
}

func (c *Client) sendGetOrgV2Environment(ctx context.Context, params GetOrgV2EnvironmentParams) (res GetOrgV2EnvironmentRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getOrgV2Environment"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/org/v2/environments/{id}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetOrgV2EnvironmentOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/org/v2/environments/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:CloudAPIKey"
			switch err := c.securityCloudAPIKey(ctx, GetOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"CloudAPIKey\"")
			}
		}
		{
			stage = "Security:GlobalAPIKey"
			switch err := c.securityGlobalAPIKey(ctx, GetOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"GlobalAPIKey\"")
			}
		}
		{
			stage = "Security:ConfluentStsAccessToken"
			switch err := c.securityConfluentStsAccessToken(ctx, GetOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 2
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"ConfluentStsAccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
				{0b00000010},
				{0b00000100},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetOrgV2EnvironmentResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetOrgV2Organization invokes getOrgV2Organization operation.
//
// [General Availability]
//
// Make a request to read an organization.
//
// [General Availability]: #section/Versioning/API-Lifecycle-Policy
//
// GET /org/v2/organizations/{id}
func (c *Client) GetOrgV2Organization(ctx context.Context, params GetOrgV2OrganizationParams) (GetOrgV2OrganizationRes, error) {
	res, err := c.sendGetOrgV2Organization(ctx, params)
	return res, err
}

func (c *Client) sendGetOrgV2Organization(ctx context.Context, params GetOrgV2OrganizationParams) (res GetOrgV2OrganizationRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getOrgV2Organization"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/org/v2/organizations/{id}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetOrgV2OrganizationOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/org/v2/organizations/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:CloudAPIKey"
			switch err := c.securityCloudAPIKey(ctx, GetOrgV2OrganizationOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"CloudAPIKey\"")
			}
		}
		{
			stage = "Security:GlobalAPIKey"
			switch err := c.securityGlobalAPIKey(ctx, GetOrgV2OrganizationOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"GlobalAPIKey\"")
			}
		}
		{
			stage = "Security:ConfluentStsAccessToken"
			switch err := c.securityConfluentStsAccessToken(ctx, GetOrgV2OrganizationOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 2
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"ConfluentStsAccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
				{0b00000010},
				{0b00000100},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetOrgV2OrganizationResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UpdateOrgV2Environment invokes updateOrgV2Environment operation.
//
// [General Availability]
//
// Make a request to update an environment.
//
// [General Availability]: #section/Versioning/API-Lifecycle-Policy
//
// PATCH /org/v2/environments/{id}
func (c *Client) UpdateOrgV2Environment(ctx context.Context, request OptOrgV2Environment, params UpdateOrgV2EnvironmentParams) (UpdateOrgV2EnvironmentRes, error) {
	res, err := c.sendUpdateOrgV2Environment(ctx, request, params)
	return res, err
}

func (c *Client) sendUpdateOrgV2Environment(ctx context.Context, request OptOrgV2Environment, params UpdateOrgV2EnvironmentParams) (res UpdateOrgV2EnvironmentRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("updateOrgV2Environment"),
		semconv.HTTPRequestMethodKey.String("PATCH"),
		semconv.URLTemplateKey.String("/org/v2/environments/{id}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, UpdateOrgV2EnvironmentOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/org/v2/environments/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PATCH", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUpdateOrgV2EnvironmentRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:CloudAPIKey"
			switch err := c.securityCloudAPIKey(ctx, UpdateOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"CloudAPIKey\"")
			}
		}
		{
			stage = "Security:GlobalAPIKey"
			switch err := c.securityGlobalAPIKey(ctx, UpdateOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"GlobalAPIKey\"")
			}
		}
		{
			stage = "Security:ConfluentStsAccessToken"
			switch err := c.securityConfluentStsAccessToken(ctx, UpdateOrgV2EnvironmentOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 2
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"ConfluentStsAccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
				{0b00000010},
				{0b00000100},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeUpdateOrgV2EnvironmentResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UpdateOrgV2Organization invokes updateOrgV2Organization operation.
//
// [General Availability]
//
// Make a request to update an organization.
//
// [General Availability]: #section/Versioning/API-Lifecycle-Policy
//
// PATCH /org/v2/organizations/{id}
func (c *Client) UpdateOrgV2Organization(ctx context.Context, request OptOrgV2Organization, params UpdateOrgV2OrganizationParams) (UpdateOrgV2OrganizationRes, error) {
	res, err := c.sendUpdateOrgV2Organization(ctx, request, params)
	return res, err
}

func (c *Client) sendUpdateOrgV2Organization(ctx context.Context, request OptOrgV2Organization, params UpdateOrgV2OrganizationParams) (res UpdateOrgV2OrganizationRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("updateOrgV2Organization"),
		semconv.HTTPRequestMethodKey.String("PATCH"),
		semconv.URLTemplateKey.String("/org/v2/organizations/{id}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, UpdateOrgV2OrganizationOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/org/v2/organizations/"
	{
		// Encode "id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PATCH", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUpdateOrgV2OrganizationRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:CloudAPIKey"
			switch err := c.securityCloudAPIKey(ctx, UpdateOrgV2OrganizationOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"CloudAPIKey\"")
			}
		}
		{
			stage = "Security:GlobalAPIKey"
			switch err := c.securityGlobalAPIKey(ctx, UpdateOrgV2OrganizationOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 1
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"GlobalAPIKey\"")
			}
		}
		{
			stage = "Security:ConfluentStsAccessToken"
			switch err := c.securityConfluentStsAccessToken(ctx, UpdateOrgV2OrganizationOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 2
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"ConfluentStsAccessToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
				{0b00000010},
				{0b00000100},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeUpdateOrgV2OrganizationResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
