// Code generated by ogen, DO NOT EDIT.
package srcm

type CreateSrcmV2ClusterRes interface {
	createSrcmV2ClusterRes()
}

type DeleteSrcmV2ClusterRes interface {
	deleteSrcmV2ClusterRes()
}

type GetSrcmV2ClusterRes interface {
	getSrcmV2ClusterRes()
}

type GetSrcmV2RegionRes interface {
	getSrcmV2RegionRes()
}

type GetSrcmV3ClusterRes interface {
	getSrcmV3ClusterRes()
}

type ListSrcmV2ClustersRes interface {
	listSrcmV2ClustersRes()
}

type ListSrcmV3ClustersRes interface {
	listSrcmV3ClustersRes()
}

type UpdateSrcmV2ClusterRes interface {
	updateSrcmV2ClusterRes()
}
