// Code generated by ogen, DO NOT EDIT.

package sql

import (
	"encoding/binary"
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for SQLV1MaterializedTableVersion using FNV-1a.
// Equal objects must produce equal hashes.
func (a SQLV1MaterializedTableVersion) Hash() uint64 {
	h := fnv.New64a()

	// Hash primitive field: APIVersion
	h.Write([]byte(fmt.Sprintf("%v", a.APIVersion)))
	// Hash primitive field: Kind
	h.Write([]byte(fmt.Sprintf("%v", a.Kind)))
	// Hash nested object: Metadata
	nestedHashMetadata := a.Metadata.Hash()
	binary.Write(h, binary.LittleEndian, nestedHashMetadata)
	// Hash primitive field: Name
	h.Write([]byte(fmt.Sprintf("%v", a.Name)))
	// Hash primitive field: OrganizationID
	h.Write([]byte(fmt.Sprintf("%v", a.OrganizationID)))
	// Hash primitive field: EnvironmentID
	h.Write([]byte(fmt.Sprintf("%v", a.EnvironmentID)))
	// Hash nested object: Spec
	nestedHashSpec := a.Spec.Hash()
	binary.Write(h, binary.LittleEndian, nestedHashSpec)
	return h.Sum64()
}
