// Code generated by ogen, DO NOT EDIT.

package sql

import "github.com/ogen-go/ogen/validate"

// Equal compares two SQLV1AgentSpec instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a SQLV1AgentSpec) Equal(b SQLV1AgentSpec, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "SQLV1AgentSpec",
		})
	}

	// Compare optional field: Description
	if a.Description.Set != b.Description.Set {
		return false
	}
	if a.Description.Set {
		if a.Description.Value != b.Description.Value {
			return false
		}
	}
	// Compare optional field: Model
	if a.Model.Set != b.Model.Set {
		return false
	}
	if a.Model.Set {
		if a.Model.Value != b.Model.Value {
			return false
		}
	}
	// Compare optional field: Prompt
	if a.Prompt.Set != b.Prompt.Set {
		return false
	}
	if a.Prompt.Set {
		if a.Prompt.Value != b.Prompt.Value {
			return false
		}
	}
	// Compare array field: Tools
	if len(a.Tools) != len(b.Tools) {
		return false
	}
	for i := range a.Tools {
		if a.Tools[i] != b.Tools[i] {
			return false
		}
	}
	// Compare optional field: Properties
	if a.Properties.Set != b.Properties.Set {
		return false
	}
	if a.Properties.Set {
		if len(a.Properties.Value) != len(b.Properties.Value) {
			return false
		}
		for k, v := range a.Properties.Value {
			if bv, ok := b.Properties.Value[k]; !ok || v != bv {
				return false
			}
		}
	}
	return true
}
