// Code generated by ogen, DO NOT EDIT.

package exporters

import (
	"bytes"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
)

func encodeRegisterExporterRequest(
	req RegisterExporterReq,
	r *http.Request,
) error {
	switch req := req.(type) {
	case *RegisterExporterApplicationJSON:
		const contentType = "application/json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *RegisterExporterApplicationVndSchemaregistryJSON:
		const contentType = "application/vnd.schemaregistry+json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *RegisterExporterApplicationVndSchemaregistryV1JSON:
		const contentType = "application/vnd.schemaregistry.v1+json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	default:
		return errors.Errorf("unexpected request type: %T", req)
	}
}

func encodeUpdateExporterConfigByNameRequest(
	req UpdateExporterConfigByNameReq,
	r *http.Request,
) error {
	switch req := req.(type) {
	case *UpdateExporterConfigByNameApplicationJSON:
		const contentType = "application/json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *UpdateExporterConfigByNameApplicationVndSchemaregistryJSON:
		const contentType = "application/vnd.schemaregistry+json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *UpdateExporterConfigByNameApplicationVndSchemaregistryV1JSON:
		const contentType = "application/vnd.schemaregistry.v1+json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	default:
		return errors.Errorf("unexpected request type: %T", req)
	}
}

func encodeUpdateExporterInfoRequest(
	req UpdateExporterInfoReq,
	r *http.Request,
) error {
	switch req := req.(type) {
	case *UpdateExporterInfoApplicationJSON:
		const contentType = "application/json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *UpdateExporterInfoApplicationVndSchemaregistryJSON:
		const contentType = "application/vnd.schemaregistry+json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *UpdateExporterInfoApplicationVndSchemaregistryV1JSON:
		const contentType = "application/vnd.schemaregistry.v1+json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	default:
		return errors.Errorf("unexpected request type: %T", req)
	}
}
