// Code generated by ogen, DO NOT EDIT.

package endpoint

// OperationName is the ogen operation name
type OperationName = string

const (
	ListEndpointV1EndpointsOperation OperationName = "ListEndpointV1Endpoints"
)
